#!/usr/bin/env sh

# Sourced the xcolors init.sh
# . $HOME/lib/xorg/xcolor.sh

# System function

cpu() {

    cpu="$(cat /proc/loadavg | awk '{print $1}')"
    out="[CPU %{F${RED}}${cpu}%{F-}]"
    
    echo -n $out
}
