#!/usr/bin/env sh

# Sourced the xcolors init.sh
# . $HOME/lib/xorg/xcolor.sh

# TODO:
#   * Needs to figure out which card we are using

volume() {

    status=$(amixer get Master | grep 'off')
    vol=$(amixer get Master | grep 'Mono:' | \
            awk '{print $4}' | tr -d '[]')

    if [ -z "$status" ]; then
        out="[VOL %{F${CYAN}}${vol}%{F-}]"
    else
        out="[VOL %{F${RED}}MUTED%{F-}]"
    fi
    echo -n $out
}
