:PROPERTIES:
:ID:       60f90e10-9f05-45f1-8567-925e7dafcc95
:ROAM_ALIASES: bibtex-mode
:END:
#+TITLE: BibTeX
#+AUTHOR: Amlesh Sivanantham (zamlz)
#+CREATED: [2021-05-26 Wed 08:08]
#+LAST_MODIFIED: [2021-10-14 Thu 17:02:58]
#+STARTUP: content
#+FILETAGS: :config:emacs:

* Manage Bibliography Entries
=BibTeX= is pimarily used by [[id:81f184a7-8c7a-40c7-9384-b7bd117a0e1c][LaTeX]] to manage bibliography entries.
[[id:cf447557-1f87-4a07-916a-160cfd2310cf][GNU/Emacs]] already provides a major-mode for editing =BibTeX= files.

* Configuration
:PROPERTIES:
:header-args:emacs-lisp: :tangle ~/.config/emacs/lisp/init-bibtex.el :comments both :mkdirp yes
:END:
** Setup Spellcheking
In =bibtex-mode= buffers, let's also have spell checking setup. Can't be writing citations with typos. We incorporate =flyspell= which is part of the [[id:e565a047-e13a-425d-b86e-e0ea33887e17][Flycheck Syntax Checking]] package.

#+begin_src emacs-lisp
(require 'init-flycheck)
(add-hook 'bibtex-mode-hook 'flyspell-mode)
#+end_src

** User Defined Fields
We can have specially defined fields that are not normally added by =bibtex-mode=.

#+begin_src emacs-lisp
(setq bibtex-user-optional-fields
      '(("keywords" "Keywords to describe the entry" "")))
#+end_src

Disable the use of OTP keys.

#+begin_src emacs-lisp
(setq bibtex-include-OPTkey nil)
#+end_src

** Alignment
Let's make =bibtex-mode='s formatting more pretty

#+begin_src emacs-lisp
(setq bibtex-align-at-equal-sign t)
#+end_src

** Org Export Support
We should provide =BibTeX= export support for [[id:ef93dff4-b19f-4835-9002-9d4215f8a6fe][Org-mode]]. Make sure to pull in [[id:ef93dff4-b19f-4835-9002-9d4215f8a6fe][Org-mode]] first however!

#+begin_src emacs-lisp
(require 'init-org)
#+end_src

What we want to do is change the build command for [[id:81f184a7-8c7a-40c7-9384-b7bd117a0e1c][LaTeX]] in [[id:ef93dff4-b19f-4835-9002-9d4215f8a6fe][Org-mode]] to support the =BibTeX= as well. By using =latexmk=, as its runs =pdflatex= the correct number of times and also runs =bibtex= as well to ensure references are correctly built.

#+begin_src emacs-lisp
(setq org-latex-pdf-process '("latexmk -pdf -outdir=%o %f"))
#+end_src

** Feature Provide

#+begin_src emacs-lisp
(provide 'init-bibtex)
#+end_src
