#+TITLE: BibTeX Actions
#+AUTHOR: Amlesh Sivanantham (zamlz)
#+ROAM_ALIAS:
#+ROAM_TAGS: CONFIG SOFTWARE
#+CREATED: [2021-05-20 Thu 19:43]
#+LAST_MODIFIED: [2021-05-29 Sat 12:13:32]
#+STARTUP: content

* Quickly Find and Act on BibTeX Entries

=bibtex-actions= is a package that is meant to quickly find [[file:bibtex.org][BibTeX]] entries using the [[file:bibtex_completions.org][BibTeX Completions]] backend via completion frameworks like [[file:vertico.org][Vertico]], also adding various actions that can be run via [[file:embark.org][Embark]].

* Configuration
:PROPERTIES:
:header-args:emacs-lisp: :tangle ~/.config/emacs/lisp/init-bibtex-actions.el :comments both :mkdirp yes
:END:

** Setup Dependencies

We really just need to make sure [[file:embark.org][Embark]] is configured first probably.

#+begin_src emacs-lisp
(require 'init-embark)
#+end_src

More importantly, =bibtex-actions= makes use of [[file:bibtex_completions.org][BibTeX Completions]] which needs to be configured as well.

#+begin_src emacs-lisp
(require 'init-bibtex-completions)
#+end_src

** Package Install

While setting up the package.

#+begin_src emacs-lisp
(use-package bibtex-actions
  :after embark
  :config (add-to-list 'embark-keymap-alist '(bibtex  . bibtex-actions-map)))
#+end_src

** Setup Action Inputs
I prefer to have the initial inputs for the various commands setup a little differently. Find it more intuitive.

#+begin_src emacs-lisp
(setq bibtex-actions-initial-inputs
  '((pdf    . "has:pdf")
    (note   . "has:note")
    (link   . "has:link")
    (source . nil)))
#+end_src

** Configure Template

#+begin_src emacs-lisp
(setq bibtex-actions-template
      '((t . "${author:20}   ${title:48}   ${year:4}")))
(setq bibtex-actions-template-suffix
      '((t . "          ${=key=:15}    ${=type=:12}    ${tags:*}")))
#+end_src

** All-the-icons Integration

#+begin_src emacs-lisp
(setq bibtex-actions-symbols
  `((pdf . (,(all-the-icons-icon-for-file "foo.pdf" :face 'all-the-icons-dred) .
            ,(all-the-icons-icon-for-file "foo.pdf" :face 'bibtex-actions-icon-dim)))
    (note . (,(all-the-icons-icon-for-file "foo.txt") .
            ,(all-the-icons-icon-for-file "foo.txt" :face 'bibtex-actions-icon-dim)))
    (link .
        (,(all-the-icons-faicon "external-link-square" :v-adjust 0.02 :face 'all-the-icons-dpurple) .
        ,(all-the-icons-faicon "external-link-square" :v-adjust 0.02 :face 'bibtex-actions-icon-dim)))))
#+end_src

Here we define a face to dim non 'active' icons, but preserve alignment

#+begin_src emacs-lisp
(defface bibtex-actions-icon-dim
    '((((background dark)) :foreground "#282c34")
     (((background light)) :foreground "#fafafa"))
     "Face for obscuring/dimming icons"
     :group 'all-the-icons-faces)
#+end_src

** Feature Provide

#+begin_src emacs-lisp
(provide 'init-bibtex-actions)
#+end_src
