#+TITLE: Major Mode Hydra
#+AUTHOR: Amlesh Sivanantham (zamlz)
#+ROAM_KEY: https://github.com/jerrypnz/major-mode-hydra.el
#+ROAM_ALIAS:
#+ROAM_TAGS: CONFIG SOFTWARE
#+CREATED: [2021-05-08 Sat 17:00]
#+LAST_MODIFIED: [2021-05-28 Fri 07:56:32]

* Major Mode Hydra and Pretty Hydra
A pretty nice package that let's us define specific [[file:hydra.org][Hydra]] menus for specific meajor-modes in [[file:emacs.org][GNU/Emacs]].

* Configuration
:PROPERTIES:
:header-args:emacs-lisp: :tangle ~/.config/emacs/lisp/init-major-mode-hydra.el :comments both :mkdirp yes
:END:

** Setup Hydra
Ensure that [[file:hydra.org][Hydra]] is configured first.

#+begin_src emacs-lisp
(require 'init-hydra)
#+end_src

** Package Install
Now we can configure this package.

#+begin_src emacs-lisp
(use-package major-mode-hydra
  :after hydra)
#+end_src

** Configure Major-mode Keybindings
We also want to be able to access the =major-mode-hydra= menu as easily as possible so let's add that to our [[file:general_el.org][General Leader Keybindings Definer]].

#+begin_src emacs-lisp
(require 'init-general)
(zamlz/leader-keys
  "SPC" 'major-mode-hydra)
#+end_src

** Personal Hydras
*** Notetaking
Let's define a =hydra= for accessing all notetaking related functions in packages like [[file:org_roam.org][Org-roam]] and [[file:bibtex_actions.org][BibTeX Actions]]. We don't need to worry about setting up the dependencies as they will be setup at some point, =hydra= will automatically find them when the function is run.

#+begin_src emacs-lisp
(pretty-hydra-define zamlz/hydra-notes
  (:title "Notetaking Commands" :color blue :quit-key "q" :exit t)
  ("Roam"
   (("l" org-roam "Show Backlinks" :toggle t)
    ("/" org-roam-find-file "Find File")
    ("g" org-roam-graph "Graph View")
    ("t" org-roam-tag-add "Add Tags")
    ("a" org-roam-alias-add "Add Alias"))
   "BibTeX"
   (("b" bibtex-actions-open "Library")
    ("n" bibtex-actions-open-notes "Notes")
    ("p" bibtex-actions-open-pdf "PDF")
    ("L" bibtex-actions-open-link "Open Link")
    ("e" bibtex-actions-open-entry "View Entry"))
   "Journal"
   ()
   "Misc"
   (("r" zamlz/notetaking-system-refresh "Refresh"))))
#+end_src

Add the notetaking =hydra= to [[file:general_el.org][General Leader Keybindings Definer]].

#+begin_src emacs-lisp
(zamlz/leader-keys
  "n" 'zamlz/hydra-notes/body)
#+end_src

We also create a single function that will refresh all parts of our notetaking system.

#+begin_src emacs-lisp
(defun zamlz/notetaking-system-refresh()
  "Refreshes Org-Roam and Bibtex-Actions"
  (interactive)
  (org-roam-db-build-cache)
  (bibtex-actions-refresh))
#+end_src

*** Documentation & Help
Create a =hydra= for accessing all help documentation super easily and also provide bindings for packages like [[file:helpful.org][Helpful]].

#+begin_src emacs-lisp
(pretty-hydra-define zamlz/hydra-documentation
  (:title "Help & Documentation Commands" :color green :quit-key "q" :exit t)
  ("CMDs/Funcs/Macros"
   (("h" helpful-callable "[ALL]")
    ("c" helpful-command "Command")
    ("f" helpful-function "Function")
    ("m" helpful-macro "Macro"))
  "Variable"
   (("v" helpful-variable "Variable")
    ("V" set-variable "Set Variable")
    ("s" helpful-at-point "Symbol at Point"))
  "Keybindings"
   (("k" helpful-key "Describe Key")
    ("b" embark-bindings "List Bindings")
    )))
#+end_src

Add the documentation & help =hydra= to [[file:general_el.org][General Leader Keybindings Definer]].

#+begin_src emacs-lisp
(zamlz/leader-keys
  "h" 'zamlz/hydra-documentation/body)
#+end_src

** Feature Provide
Make sure to provide this module

#+begin_src emacs-lisp
(provide 'init-major-mode-hydra)
#+end_src
