#+TITLE: Org-ref
#+AUTHOR: Amlesh Sivanantham (zamlz)
#+ROAM_KEY: https://github.com/jkitchin/org-ref
#+ROAM_TAGS: CONFIG SOFTWARE
#+CREATED: [2021-05-29 Sat 12:27]
#+LAST_MODIFIED: [2021-05-31 Mon 11:45:12]
#+STARTUP: content

* Citations, Cross-References, Indexes, Glossaries for Org
=Org-ref= is a packae that adds various types of refences and links for [[file:org_mode.org][Org-mode]]. It also provides a variety os sub-packages for downloading bibtex references and PDFs from various sources like =ArXiV= , DOI, and many more.

\begin{equation}
\label{mytesteq}
y = \sinh x
\end{equation}

We can also insert links to papers like so, citet:holden2017

* Configuration
:PROPERTIES:
:header-args:emacs-lisp: :tangle ~/.config/emacs/lisp/init-org-ref.el :comments both :mkdirp yes
:END:

** Setup Dependencies
[[file:bibtex_completions.org][BibTeX Completions]] isn't actually necessary for this package, but since we use, we want to make sure that we use the same path variables for =Org-ref= so Let's load that in.

#+begin_src emacs-lisp
(require 'init-bibtex-completions)
#+end_src

[[file:org_mode.org][Org-mode]] needs to also be loaded.

#+begin_src emacs-lisp
(require 'init-org)
#+end_src

** Package Install

#+begin_src emacs-lisp
(use-package org-ref)
#+end_src

** Sync Library Path
As mentioned before, let's make sure to sync our library path with [[file:bibtex_completions.org][BibTeX Completions]]. /Also =org-ref= needs full file paths for some reason.../

#+begin_src emacs-lisp
(setq reftex-default-bibliography bibtex-completion-bibliography)
(setq org-ref-bibliography-notes nil)
(setq org-ref-default-bibliography bibtex-completion-bibliography)
(setq org-ref-pdf-directory (car bibtex-completion-library-path))
#+end_src

**  Prefer User Labels for LaTeX
When exporting to [[file:latex.org][LaTeX]], let's make sure to tell the exporting process that we wish to use our own defined variables.

#+begin_src emacs-lisp
(setq org-latex-prefer-user-labels t)
#+end_src

** Setup LaTeX Package Support for References
We need to add a few packages for [[file:latex.org][LaTeX]] to load up so that exporting with [[file:bibtex.org][BibTeX]] references works properly.

#+begin_src emacs-lisp
(add-to-list 'org-latex-default-packages-alist '("" "natbib" nil) t)
(add-to-list 'org-latex-default-packages-alist '("" "cleveref" nil) t)
#+end_src

** Feature Provide

#+begin_src emacs-lisp
(provide 'init-org-ref)
#+end_src

* Bibliography Test
We can now reference this equation like so, eqref:mytesteq

bibliographystyle:authordate1
bibliography:/home/zamlz/org/papers/references.bib
