:PROPERTIES:
:ID:       355790b5-0daa-48a4-bd64-566b4c93ca9b
:ROAM_REFS: https://github.com/jkitchin/org-ref
:END:
#+TITLE: Org-ref
#+AUTHOR: Amlesh Sivanantham (zamlz)
#+CREATED: [2021-05-29 Sat 12:27]
#+LAST_MODIFIED: [2021-07-19 Mon 09:43:22]
#+STARTUP: content
#+filetags: CONFIG SOFTWARE

* Citations, Cross-References, Indexes, Glossaries for Org
=Org-ref= is a packae that adds various types of refences and links for [[id:ef93dff4-b19f-4835-9002-9d4215f8a6fe][Org-mode]]. It also provides a variety os sub-packages for downloading bibtex references and PDFs from various sources like =ArXiV= , DOI, and many more.

\begin{equation}
\label{mytesteq}
y = \sinh x
\end{equation}

We can also insert links to papers like so, citet:holden2017

* Configuration
:PROPERTIES:
:header-args:emacs-lisp: :tangle ~/.config/emacs/lisp/init-org-ref.el :comments both :mkdirp yes
:END:

** Setup Dependencies
[[id:88776879-cbf7-449e-88cf-305cafd1a0c3][BibTeX Completions]] isn't actually necessary for this package, but since we use, we want to make sure that we use the same path variables for =Org-ref= so Let's load that in.

#+begin_src emacs-lisp
(require 'init-bibtex-completions)
#+end_src

[[id:ef93dff4-b19f-4835-9002-9d4215f8a6fe][Org-mode]] needs to also be loaded.

#+begin_src emacs-lisp
(require 'init-org)
#+end_src

** Package Install

#+begin_src emacs-lisp
(use-package org-ref)
#+end_src

** Sync Library Path
As mentioned before, let's make sure to sync our library path with [[id:88776879-cbf7-449e-88cf-305cafd1a0c3][BibTeX Completions]]. /Also =org-ref= needs full file paths for some reason.../

#+begin_src emacs-lisp
(setq reftex-default-bibliography bibtex-completion-bibliography)
(setq org-ref-bibliography-notes nil)
(setq org-ref-default-bibliography bibtex-completion-bibliography)
(setq org-ref-pdf-directory (car bibtex-completion-library-path))
#+end_src

**  Prefer User Labels for LaTeX
When exporting to [[id:81f184a7-8c7a-40c7-9384-b7bd117a0e1c][LaTeX]], let's make sure to tell the exporting process that we wish to use our own defined variables.

#+begin_src emacs-lisp
(setq org-latex-prefer-user-labels t)
#+end_src

** Setup LaTeX Package Support for References
We need to add a few packages for [[id:81f184a7-8c7a-40c7-9384-b7bd117a0e1c][LaTeX]] to load up so that exporting with [[id:60f90e10-9f05-45f1-8567-925e7dafcc95][BibTeX]] references works properly.

#+begin_src emacs-lisp
(add-to-list 'org-latex-default-packages-alist '("" "natbib" nil) t)
(add-to-list 'org-latex-default-packages-alist '("" "cleveref" nil) t)
#+end_src

** Feature Provide

#+begin_src emacs-lisp
(provide 'init-org-ref)
#+end_src

* Bibliography Test
We can now reference this equation like so, eqref:mytesteq

bibliographystyle:authordate1
bibliography:/home/zamlz/org/papers/references.bib
