:PROPERTIES:
:ID:       a2b556d7-a664-4b17-be7c-a42f7ddf72af
:ROAM_REFS: https://github.com/baskerville/sxhkd
:ROAM_ALIASES: sxhkd
:END:
#+TITLE: Sxhkd Hotkey Daemon
#+AUTHOR: Amlesh Sivanantham (zamlz)
#+CREATED: [2021-03-29 Mon 19:28]
#+LAST_MODIFIED: [2021-07-19 Mon 09:43:24]
#+filetags: CONFIG SOFTWARE

Sxhkd is a hotkey daemon for the [[id:9d70bac0-d660-47f4-b9bc-2f2531951f13][Xorg X11 Window System]].

* Configuration
:PROPERTIES:
:header-args:shell: :tangle ~/.config/sxhkd/sxhkdrc :mkdirp yes :comments both
:END:
** Startup Script
:PROPERTIES:
:header-args:shell: :tangle ~/.config/xinitrc.d/sxhkd-refresh.sh :mkdirp yes :shebang #!/bin/sh :comments both
:END:

We need to configure =sxhkd= to startup and refresh whenever our window manager is refreshed. Add this snippet to the [[id:64c66aeb-1b89-4f51-8e36-2931fb24399a][xinit]] user-level scripts.

#+begin_src shell
SXHKD_SHELL=sh
export SXHKD_TERMINAL=$HOME/org/config/bin/emacsclient-launcher
pkill -x sxhkd
sxhkd &
#+end_src

** Terminal Exec Keybindings

Keybinding to spawn a terminal. This variable is defined in the [[id:9d70bac0-d660-47f4-b9bc-2f2531951f13][X11]] window manager utilities init file.

#+begin_src shell
super + Return
    $SXHKD_TERMINAL
#+end_src

Spawn Terminal matching environment of focused terminal. This is incredibly useful if I want to create another terminal instance in the same directory as the one I'm currently in. /This actually only works in normal terminals and and not in the emacs vterm. Need to think of another solution to handle that but probably don't need to./

#+begin_src shell
super + shift + Return
    $HOME/org/config/lib/pwdcfw/$SXHKD_TERMINAL
#+end_src

** Rofi Dmenu Launcher Keybindings

Here we make use of [[id:962dd4f7-01dc-4b3f-8fbf-fa1b480735ca][Rofi Dmenu]] to create various dmenus to do various tasks. Half of these are probably deprecated now that I'm using emacs, but nonetheless, here they are.

Dmenu for launching a program from =$PATH=.

#+begin_src shell
super + e
    rofi -show run
#+end_src

Dmenu for listing all open windows and changing focus.

#+begin_src shell
super + w
    rofi -show window
#+end_src

Dmenu for interacting with password store and also getting QR Code view.

#+begin_src shell
super + p
    $HOME/org/config/lib/rofi/rofi-pass
super + shift + p
    $HOME/org/config/lib/rofi/rofi-pass --qrcode
#+end_src

Dmenu for retrieving and saving personal bookmarks /(Deprecated in favor of Org-roam)/

#+begin_src shell
super + b
    $HOME/org/config/lib/rofi/rofi-book
#+end_src

Dmenu for looking up my vimwiki files in read-only mode. Also generate PDF views as well. /(Deprecated in favor of Org-roam)/

#+begin_src shell
super + n
    $HOME/org/config/lib/rofi/rofi-wiki
super + shift + n
    $HOME/org/config/lib/rofi/rofi-wiki --pdf
#+end_src

Choose which [[id:70241ca3-43a7-416c-8d09-ad1e1c6666c6][Qutebrowser]] session to load. Unforunately its pretty buggy and is not working the way I expect.

#+begin_src shell
super + shift + w
    $HOME/org/config/lib/rofi/rofi-browser
#+end_src

Toggle between different display/power profile (multi-monitor, single monitor, etc.)

#+begin_src shell
super + d
    $HOME/org/config/lib/rofi/rofi-profile
XF86Display
    $HOME/org/config/lib/rofi/rofi-profile
#+end_src

Dmenu to control system state (locked, reboot, poweroff, etc.)

#+begin_src shell
#super + Escape
#    $HOME/org/config/lib/rofi/rofi-system LOCK SCREEN
super + ctrl + alt + Escape
    $HOME/org/config/lib/rofi/rofi-system
#+end_src

** Scrot Keybindings

Interactively select a window or rectangle with the mouse to take a screen shot of it. /It's important that these keybindings are prefaces with the =@= token as it implies that the command should be executed on key release as opposed to key press. Scrot and xclip here will not work properly unless they are on key release./

#+begin_src shell
@Print
    scrot -q 100 -s '/tmp/%F_%T_$wx$h.png' -e 'xclip -selection clipboard -target image/png -i $f'

@shift + Print
    scrot -q 100 '/tmp/%F_%T_$wx$h.png' -e 'xclip -selection clipboard -target image/png -i $f'
#+end_src

** Media Control Keybindings

Various media keybindings that both actually do the what the media key describes and also /(usually)/ sends a signal to the [[id:e85b69f9-e309-4d26-9516-2e79524ffe00][Lemonbar]] FIFOs.

#+begin_src shell
XF86MonBrightnessUp
    xbacklight -inc 1 -time 10; \
    $HOME/.config/lemonbar/utils/trigger_fifos bkl

XF86MonBrightnessDown
    xbacklight -dec 1 -time 10; \
    $HOME/.config/lemonbar/utils/trigger_fifos bkl

XF86AudioMute
    pulsemixer --toggle-mute; \
    $HOME/.config/lemonbar/utils/trigger_fifos vol

XF86AudioMicMute
    pulsemixer --toggle-mute; \
    $HOME/.config/lemonbar/utils/trigger_fifos vol

XF86AudioRaiseVolume
    pulsemixer --change-volume +1; \
    $HOME/.config/lemonbar/utils/trigger_fifos vol

XF86AudioLowerVolume
    pulsemixer --change-volume -1; \
    $HOME/.config/lemonbar/utils/trigger_fifos vol

XF86AudioPlay
    $HOME/src/spotify-cli/spotify-cli toggle

XF86AudioNext
    $HOME/src/spotify-cli/spotify-cli next

XF86AudioPrev
    $HOME/src/spotify-cli/spotify-cli prev
#+end_src
