:PROPERTIES:
:ID:       5b41aa58-7edc-4467-957d-d2383e816d57
:END:
#+TITLE: XDG Utils
#+AUTHOR: Amlesh Sivanantham (zamlz)
#+CREATED: [2021-05-05 Wed 08:03]
#+LAST_MODIFIED: [2021-07-19 Mon 09:43:12]
#+filetags: CONFIG SOFTWARE

XDG Utils is a set of utilities for managing XDG MIME Applications. The provide an interface to open files with a specific /default/ application and also configure various directories.

* Tips and Tricks

Not much here yet

* Useful Resources
- [[https://wiki.archlinux.org/title/Xdg-utils][Arch Linux Wiki: XDG Utils]]
- [[https://wiki.archlinux.org/title/XDG_Base_Directory][Arch Linux Wiki: XDG Base Directory]]

* Configuration
** Setup Base Directories
:PROPERTIES:
:header-args:shell: :tangle ~/.config/user-dirs.dirs
:END:

Don't use a traditional desktop environment so there is not need for a seperate desktop directory. I let this be my home directory.

#+begin_src shell
XDG_DESKTOP_DIR="$HOME/"
#+end_src

I don't really have a documents diretory really so I just store everything in here. Most of my real documents are all org files, so they only exist in git repos anyway.

#+begin_src shell
XDG_DOCUMENTS_DIR="$HOME/usr"
#+end_src

I actually save all downloads to a local folder named =tmp=. All of its contents are deleted on poweroff so it forces me to organize files that I download right away.

#+begin_src shell
XDG_DOWNLOAD_DIR="$HOME/tmp"
#+end_src

I don't really download music at the moment so I just set this generic location for now.


#+begin_src shell
XDG_MUSIC_DIR="$HOME/usr"
#+end_src

The same goes with pictures...

#+begin_src shell
XDG_PICTURES_DIR="$HOME/usr"
#+end_src

And videos as well...

#+begin_src shell
XDG_VIDEOS_DIR="$HOME/usr"
#+end_src

I'm public share directory is a directory that has read access for all users on the system. However, since I'm the only user on the system, I don't really use this.

#+begin_src shell
XDG_PUBLICSHARE_DIR="$HOME/tmp"
#+end_src

I don't really manage templates of any kind. Maybe I should...

#+begin_src shell
XDG_TEMPLATES_DIR="$HOME/tmp"
#+end_src
