#!/bin/sh

. $HOME/etc/lemonbar/config

while true; do
    msg=$(xbacklight -get)
    msg=$($MSG_WRAPPER $ICON_BACKLIGHT $YELLOW $msg)
    echo "$ANCHOR_BACKLIGHT$msg"
    sleep $REFRESH_BACKLIGHT
done

# vim: set ft=sh:
