#!/bin/sh

. $HOME/etc/lemonbar/config

while true; do
    msg="$(xbacklight -get | sed -e 's/\.[0-9]*//g')%"
    msg=$($MSG_WRAPPER $ICON_BACKLIGHT $BLUE $msg)
    echo "$ANCHOR_BACKLIGHT$msg"
    sleep $REFRESH_BACKLIGHT
done

# vim: set ft=sh:
