#!/bin/sh

# Need to import again in case we use it as a standalone script
. $HOME/lib/shell/xrdb_colors
. $HOME/etc/lemonbar/wrappers
wrapper=${MSG_WRAPPER:-debug_wrapper}

REFRESH_LIGHT=1
ICON="BKL"

while true; do
    msg=$(xbacklight -get)
    msg=$($wrapper $ICON $YELLOW $msg)
    echo "BACKLIGHT$msg"
    sleep $REFRESH_LIGHT
done

# vim: set ft=sh:
