#!/bin/sh

# Need to import again in case we use it as a standalone script
. $HOME/lib/shell/xrdb_colors
. $HOME/etc/lemonbar/config
wrapper=${MSG_WRAPPER:-debug_wrapper}

REFRESH_BATTERY=2
ICON="BAT"

while true; do
    batloc="/sys/class/power_supply/"
    batlist=$(ls $batloc | grep "BAT")
    out=""

    if [ -n "${batlist}" ]; then
        for bat in $batlist; do
            cap="$(cat ${batloc}${bat}/capacity)"
            stat="$(cat ${batloc}${bat}/status)"
            batid=$(echo $bat | tr -d 'BAT')
            out="${out} ${batid}:${cap}"

        done
    else
        out="${out} A/C"
    fi

    msg="[$ICON $out]"
    echo "BATTERY$msg"
    sleep $REFRESH_BATTERY
done

# vim: set ft=sh:
