#!/bin/sh

. $HOME/etc/lemonbar/config

while true; do
    batloc="/sys/class/power_supply/"
    batlist=$(ls $batloc | grep "BAT")
    out=""

    if [ -n "${batlist}" ]; then
        for bat in $batlist; do
            cap="$(cat ${batloc}${bat}/capacity)"
            stat="$(cat ${batloc}${bat}/status)"
            batid=$(echo $bat | tr -d 'BAT')
            out="${out} ${batid}:${cap}"

        done
    else
        out="${out} A/C"
    fi

    msg=$($MSG_WRAPPER $ICON_BATTERY $MAGENTA $out)
    echo "BATTERY$msg"
    sleep $REFRESH_BATTERY
done

# vim: set ft=sh:
