#!/bin/sh

. $HOME/etc/lemonbar/config

# Set the refresh time to how many seconds till midnight
REFRESH_DATE=$(($(date -d 23:59:59 +%s) - $(date +%s) + 1))

while true; do
    msg=$(date +'%A, %d %B %Y')
    msg=$($MSG_WRAPPER $ICON_DATE $GREEN $msg)
    echo "CALENDAR$msg"
    sleep $REFRESH_DATE
    REFRESH_DATE=86400 # Update the seconds to total seconds in a day
done

# vim: set ft=sh:
