#!/bin/sh

. $HOME/etc/lemonbar/config

while true; do
    msg=$(date +'%l:%M:%S %p')
    msg=$($MSG_WRAPPER $ICON_TIME $GREEN $msg)
    echo "CLOCK$msg"
    sleep $REFRESH_TIME
done

# vim: set ft=sh:
