#!/bin/sh

. $HOME/etc/lemonbar/config

while true; do
    msg=""
    wifi_status=$(iw $WLAN0 link)

    # Check if wifi is online
    if [ "$wifi_status" != "Not connected." ]; then
        ssid=$(iw $WLAN0 link \
            | grep 'SSID:' \
            | sed -E "s/.*SSID:(.*)/\\1/")
        signal=$(iw $WLAN0 link \
            | grep 'signal' \
            | awk '{print $2}')
        msg="$WLAN0: $ssid ($signal dBm)"

    # Check if ethernet is online
    elif false; then
        msg="Ethernet"

    # State we are offline
    else
        msg="OFFLINE"
    fi

    msg=$($MSG_WRAPPER $ICON_NETWORK $MAGENTA $msg)
    echo "NETWORK$msg"
    sleep $REFRESH_NETWORK
done

# vim: set ft=sh:
