#!/bin/sh

# Need to import again in case we use it as a standalone script
. $HOME/lib/shell/xrdb_colors
. $HOME/etc/lemonbar/wrappers
wrapper=${MSG_WRAPPER:-debug_wrapper}

WIFI_INTERFACE="wlp82s0"
ETH_INTERFACE="enp0s31f6"
REFRESH_NETWORK=2.0
ICON="NET"

while true; do
    msg=""
    wifi_status=$(iw $WIFI_INTERFACE link)

    # Check if wifi is online
    if [ "$wifi_status" != "Not connected." ]; then
        ssid=$(iw $WIFI_INTERFACE link \
            | grep 'SSID:' \
            | sed -E "s/.*SSID:(.*)/\\1/")
        signal=$(iw $WIFI_INTERFACE link \
            | grep 'signal' \
            | awk '{print $2}')
        msg="$WIFI_INTERFACE: $ssid ($signal dBm)"

    # Check if ethernet is online
    elif false; then
        msg="Ethernet"

    # State we are offline
    else
        msg="OFFLINE"
    fi

    msg=$($wrapper $ICON $CYAN $msg)
    echo "NETWORK$msg"
    sleep $REFRESH_NETWORK
done

# vim: set ft=sh:
