#!/bin/sh

. $HOME/etc/lemonbar/config

while read -r volume_event; do
    (
    $volume_event

    stats=$(pulseaudio-ctl full-status)
    vol=$(echo $stats | awk '{print $1}')
    sink_state=$(echo $stats | awk '{print $2}')
    # source_state=$(echo $stats | awk '{print $3}')

    if [ "$sink_state" = "no" ]; then
        msg="$vol%"
        color=$CYAN
    else
        msg="MUTE"
        color=$RED
    fi
    msg="%{B$color} ${ICON_VOLUME}$msg %{B-}%{F$color}"

    echo "$ANCHOR_VOLUME$msg"
    sleep $REFRESH_VOLUME
    ) &
done

# vim: set ft=sh:
