#!/bin/sh

. $HOME/etc/lemonbar/config

wmsg="${ICON_WHOAMI}$(whoami)@$(hostname)"
umsg="${ICON_LINUX}$(uname -r)"

prm_color='#256568'
alt_color=$BLACK

msg="%{B$prm_color} $wmsg %{B-}"
msg="$msg%{F$prm_color}%{B$alt_color}${PL_R}%{F-}"
msg="$msg %{F$prm_color}$umsg%{F-} %{B-}"
msg="$msg%{F$alt_color}${PL_R}%{F-}"

echo "$ANCHOR_WHOAMI$msg"

# vim: set ft=sh:
