#!/bin/sh

# Need to import again in case we use it as a standalone script
. $HOME/lib/shell/xrdb_colors
. $HOME/etc/lemonbar/config
wrapper=${MSG_WRAPPER:-debug_wrapper}

ICON="WIN"

while read -r window_event; do
    win_active=$(xdotool getactivewindow)
    win_class=$(xprop -id $win_active \
        | grep WM_CLASS \
        | awk '{print $NF}' \
        | tr -d '"' )

    if [ -z "$win_class" ]; then
        msg="<$(xprop -root _NET_WM_NAME \
            | cut -d " " -f3- \
            | tr -d '"')>"
    else
        msg="$win_class ($win_active)"
    fi
    msg=$($wrapper $ICON $BLUE $msg)
    echo "WININFO$msg"
    sleep $REFRESH_WININFO
done

# vim: set ft=sh:
