#!/bin/bash

# Author: SuNjACk
# Source: http://crunchbang.org/forums/viewtopic.php?pid=135226#p135226
# Modified: zamlz

xdef="$HOME/.xcolorscheme"
colors=( $(sed -re '/^!/d; /^$/d; s/#define //g; s/(xcolor)([0-9]) /\10\2 /g;' $xdef | \
    grep 'xcolor[01][0-9]' | sort | sed 's/^.* //g') )

echo ${colors[0]}

echo -e "\e[1;37m
 Black    Red      Green    Yellow   Blue     Magenta   Cyan    White
 ──────────────────────────────────────────────────────────────────────\e[0m"
for i in {0..7}; do echo -en "\e[$((30+$i))m ${colors[i]} \e[0m"; done
echo
for i in {8..15}; do echo -en "\e[1;$((22+$i))m ${colors[i]} \e[0m"; done
echo -e "\n"
