#!/bin/sh

# Herbstlufwm is a manual tiling window manager for the Xorg X11 Window System.
# Every workspace has a collection of frames and each of these frames contain a
# collection of windows. The frames can be manually tiled wheras the windows in
# the frames follow one of many tiling algorithms.

# Setup the logger
. $HOME/lib/shell/logging && eval "$(get_logger $0)"
logger "Initializing herbstluftwm window manager"

# Create a helper function
alias hc="herbstclient"

logger "emitting the reload hook"
hc emit_hook reload
logger "Remove all existing keybinding"
hc keyunbind --all

# Setup the window manager rules
. $HOME/etc/herbstluftwm/rules

# Setup the window manager workspaces
. $HOME/etc/herbstluftwm/tags

# Setup the window manager keybindings
. $HOME/etc/herbstluftwm/keybinds

# Rice the window manager
. $HOME/etc/herbstluftwm/theme

# CLEAN THIS UP
# $HOME/etc/herbstlftwm/FIXME

