#!/usr/bin/env bash

# this is a simple config for herbstluftwm

# TODO:
#   * Cleanup this file. Maybe split it up into multiple pieces.

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# Reapply certain XORG settings (do not fork this)
$HOME/etc/xorg/wminit

# Apply keybindings
$HOME/etc/herbstluftwm/keybinds &

# Enable custom rules
$HOME/etc/herbstluftwm/rules &

# Set the theme
$HOME/etc/herbstluftwm/theme &

# Finally start our panel
pkill -x lemonbar; $HOME/etc/lemonbar/lemonbar &
