#!/usr/bin/env bash

# this is a simple config for herbstluftwm

# TODO:
#   * Cleanup this file. Maybe split it up into multiple pieces.

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# Reload the xresource data
xrdb -I$HOME $HOME/etc/xorg/xresources
. $HOME/lib/shell/xrdb_colors

# Set the background
if [ -f "$HOME/.fehbg" ]; then
    $HOME/.fehbg
else
    # xsetroot -mod 4 4 -bg ${XBACKGROUND} -fg ${BLACK}
    #xsetroot -bitmap ~/lib/bitmaps/tile.xbm -fg '#28292A' -bg '#010203'
    xsetroot -bitmap ~/lib/bitmaps/tile.xbm -fg '#232323' -bg '#0a0a0a'
fi

# Specify the primary terminal
# TERMINAL="urxvtc +j +ss"
TERMINAL="urxvt"

# Also have to set this here in case xorg isn't started via startx
setxkbmap -option caps:escape

# Use Display Power Management Settings to configure various things.
# + Disable screen blanking (screensaver)
xset s off
# + Increases the speed of the keyboard repeat rate
xset r rate 400 50

# Apply keybindings
$HOME/etc/herbstluftwm/keybinds &

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_transparent_width 1
hc set frame_border_width 1
hc set frame_border_active_color $XBACKGROUND
hc set frame_border_normal_color $XBACKGROUND

hc set frame_bg_transparent 1
hc set frame_bg_normal_color $XBACKGROUND
hc set frame_bg_active_color $XCOLOR8

hc set always_show_frame 0
hc set frame_gap 8
hc set frame_padding 0

#hc attr theme.active.color $WHITE
hc attr theme.active.outer_color $XBACKGROUND
hc attr theme.active.inner_color $XBACKGROUND

hc attr theme.normal.color $BLACK
hc attr theme.active.color $WHITE
hc attr theme.urgent.color orange

hc attr theme.border_width 9
hc attr theme.inner_width 3
hc attr theme.outer_width 4

hc attr theme.inner_color $XBACKGROUND
hc attr theme.outer_color $XBACKGROUND

hc attr theme.floating.border_width 9
hc attr theme.floating.inner_width 3
hc attr theme.floating.outer_width 4

hc attr theme.floating.outer_color $XBACKGROUND
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3

hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients

# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class~'(Discord|DiscordCanary)' focus=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

hc detect_monitors

PANEL_HEIGHT=24
for monitor in $(seq 0 2); do
    hc pad $monitor $PANEL_HEIGHT 0 $PANEL_HEIGHT 0
done

# Start our panel
pkill -x lemonbar
$HOME/etc/lemonbar/lemonbar &
