#!/bin/sh

# Tag Definitions (workspaces)

# Setup the logger
. $HOME/lib/shell/logging && eval "$(get_logger $0)"
logger "Initializing herbstluftwm tags"

# Create a helper function
alias hc="herbstclient"
Super=Mod4

hc rename default "λ" || true

for key in $(seq 1 9); do
    index=$(($key - 1))
    hc keybind "$Super-$key" use_index "$index"
    hc keybind "$Super-Shift-$key" move_index "$index"
done

key=0
index=9
hc keybind "$Super-$key" use_index "$index"
hc keybind "$Super-Shift-$key" move_index "$index"

# vim:ft=sh
