#!/bin/sh

# Theme Configuration

# Setup the logger
. $HOME/lib/shell/logging && eval "$(get_logger etc.herbstluftwm.theme)"
logger "Initializing herbstluftwm theme"

# Create a helper function
alias hc="herbstclient"

# Source Colorscheme
. $HOME/org/config/lib/shell/xrdb_colors

# Reset Tiling and Floating states
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# Frame Appearance
hc set frame_transparent_width 1
hc set frame_border_width 1
hc set frame_border_active_color $MAGENTA
hc set frame_border_normal_color $XBACKGROUND

hc set frame_bg_transparent 1
hc set frame_bg_normal_color $XBACKGROUND
hc set frame_bg_active_color $XCOLOR8

hc set always_show_frame 0
hc set frame_gap 0
hc set frame_padding 0

# Window Appearance
hc attr theme.active.outer_color $XBACKGROUND
hc attr theme.active.inner_color $XBACKGROUND

hc attr theme.normal.color $BLACK
hc attr theme.active.color $WHITE
hc attr theme.urgent.color orange

hc attr theme.border_width 9
hc attr theme.inner_width 3
hc attr theme.outer_width 4

hc attr theme.inner_color $XBACKGROUND
hc attr theme.outer_color $XBACKGROUND

hc attr theme.floating.border_width 9
hc attr theme.floating.inner_width 3
hc attr theme.floating.outer_width 4

hc attr theme.floating.outer_color $XBACKGROUND
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# Tree View
hc set tree_style '╾│ ├└╼─┐'


