#!/bin/sh

# Find the wiki I want and display a read only version of it

. $HOME/lib/repos

# Note this is not the typical directory of vimwiki (lookingg only in the src)
VIMWIKI_DIR=${VIMWIKI_DIR:-$HOME/usr/wiki/}/src
if [ "$1" = "pdf" ]; then
    PROMPT="Wiki [PDF]"
else
    PROMPT="Wiki"
fi

wiki=$(find -L $VIMWIKI_DIR -name "*.md" | \
    sed -e "s/.md$//g" \
        -e "/^.*diary.*$/d" \
        -e 's|'$VIMWIKI_DIR'/||g' | \
    sort | tr '\n' ' ' | \
    rofi -dmenu -i -sep ' ' -p "$PROMPT" )

if [ -n "$wiki" ]; then
    if [ "$1" = "pdf" ]; then
        $HOME/bin/md2pdf ${VIMWIKI_DIR}/${wiki}.md 2> /dev/null &
    else
        ${SXHKD_TERMINAL} -e sh \
            -c "exec nvim -R ${VIMWIKI_DIR}/${wiki}.md" 2> /dev/null &
    fi
fi
