#!/bin/sh

# Find the password I want

OPTS="LOCK SCREEN|QUIT HERBSTLUFTWM|SYSTEM POWEROFF"

# Either pass what we want to do as an argument to the script
# or get it through rofi
systask="$@"
if [ -z $systask ]; then
    systask=$( echo $OPTS | rofi -sep '|' -dmenu -i -p "SYSTEM" -lines 3)
fi

if [ "$systask" = "LOCK SCREEN" ]; then

    sleep 0.3 # this ensures that rofi is closed before scrot is run
    IMG="/tmp/.curdesk.png"
    BLUR="10x10"
    scrot $IMG
    convert $IMG -blur $BLUR $IMG
    exec i3lock -nefi $IMG

elif [ "$systask" = "QUIT HERBSTLUFTWM" ]; then

    # This can't be safe...
    # TODO: Figure out a better way to poweroff from a script
    rofi -dmenu -input /dev/null -password -lines 0 -p "SUDO QUIT HERBSTLUFTWM" | \
        sudo -S herbstclient quit

elif [ "$systask" = "SYSTEM POWEROFF" ]; then

    rofi -dmenu -input /dev/null -password -lines 0 -p "SUDO POWEROFF" | \
        sudo -S poweroff

fi
