#!/bin/sh

# Find the password I want

PROFILE_DIR="$HOME/org/config/lib/profiles"

# There must be a cleaner way to get this choice
profile=$( find  $PROFILE_DIR -not -path '*/.*' -type f | \
    sed -e "s|${PROFILE_DIR}/||g" | \
    rofi -dmenu -i -lines 3 -p "Profile" )

if [ -n "$profile" ]; then
    $PROFILE_DIR/$profile
fi
