#!/bin/sh

# Find the password I want

PROMPT="password"
if [ "$1" = "--qrcode" ]; then
    QRMODE="true"
    PROMPT="${PROMPT} [QrCode]"
fi

pass_name=$(find ~/usr/passwords -type f | grep -v "\.gpg-id" | \
    grep "\.gpg" | sed -e "s|$HOME\/usr\/passwords\/||g" -e "s|\.gpg||g" | \
    rofi -dmenu -i -p "$PROMPT" )

if [ "$pass_name" != "" ]; then
    export PINENTRY_USER_DATA='rofi'
    export PASSWORD_STORE_DIR="$HOME/usr/passwords"
    if [ -z "$QRMODE" ]; then
        pass -c $pass_name
    else
        pass --qrcode $pass_name
    fi
fi
