#!/bin/sh

# Find the password I want

NOTE_DIR="$HOME/usr/notes/notes"

# There must be a cleaner way to get this choice
note_loc=$( find -L $NOTE_DIR -name index.md | \
    sed -e 's|/index.md||g' -e "s|${NOTE_DIR}||g" -e "s|^/||g" | \
    sort | tr '\n' ' ' | sed -e "s|^ ||g" | \
    rofi -dmenu -i -sep ' ' -p "Notes" )

if [ -n "$note_loc" ]; then
    $HOME/bin/md2pdf $NOTE_DIR/$note_loc/index.md &
fi
