#!/bin/sh

# Find the password I want

pass_name=$(find ~/usr/passwords -type f | grep -v "\.gpg-id" | \
    grep "\.gpg" | sed -e "s|$HOME\/usr\/passwords\/||g" -e "s|\.gpg||g" | \
    rofi -dmenu -i -p "password" )

if [ "$pass_name" != "" ]; then
    export PINENTRY_USER_DATA='rofi'
    pass -c $pass_name
fi
