#!/bin/sh

# This script will show a list of bookmarks.
#
# ex:
#   foo/test1
#   bar/test2
#   etc/misc/test3
#
# Select the bookmark you want and its url will
# be loaded into the clipboard.
#
# If one wishes to update a bookmark, all that
# needs to be done is type the url right after
# typing out the bookmark (before pressing
# enter). The script should recongize that
# there is a new bookmark being added. This can
# also work with adding new bookmarks as well.

# TODO:
#   * Generate rofi dialogues for libra events.

# Source this file to use my colorscheme
. $HOME/lib/shell/xrdb_colors

BMEXE=$HOME/bin/book
BMLIB=$HOME/usr/bookmarks
CACHE=$HOME/.cache/bookmarks

# Creates a message that will be passed to rofi for adding bookmarks
# param $1: Name of the bookmark
# param $2: URL of the bookmark
add_bookmark_msg() {
cat <<-EOF
Are you sure you wish to add this bookmark?
NAME: <span fgcolor='$BLUE'>${1}</span>
URL:  <span fgcolor='$GREEN'>${2}</span>
EOF
}

# Ensure the cache exists
if [ ! -d "$CACHE" ]; then
    mkdir -p $CACHE
fi

# Find the current commit, if a cached list doesn't exist for it, create it
COMMIT=$(git -C ${BMLIB} rev-parse HEAD)
if [ ! -f "$CACHE/$COMMIT" ]; then
    find $BMLIB -type f |  grep -v "\.git" | \
        sed -e "s|$BMLIB\/||g" | sort > $CACHE/$COMMIT
fi

# Find the bookmark I want
bm_name=$(cat ${CACHE}/${COMMIT} | rofi -dmenu -i -p "bookmark")

# See if the user gave us a new url
bookmark=$(echo $bm_name | awk '{print $1}')
new_url=$(echo $bm_name | awk '{print $2}')

if [ "$bookmark" != "" ]; then

    if [ "$new_url" = "" ]; then
        $BMEXE clip $bookmark
    else

        prmt="(yes/no)"
        mesg=$(add_bookmark_msg ${bookmark} ${new_url})
        opt=$(rofi -dmenu -input /dev/null -mesg "${mesg}" -p "$prmt" -lines 0)

        if [ "$opt" = "yes" ]; then
            export PINENTRY_USER_DATA='rofi' # this lets gpg use rofi
            $BMEXE add $bookmark $new_url
        fi
    fi
fi
