#!/bin/sh

# Find the wiki I want
VIMWIKI_DIR="$HOME/usr/wiki"

wiki=$(find -L $VIMWIKI_DIR -name "*.md" | \
    sed -e "s/.md$//g" \
        -e "/^.*diary.*$/d" \
        -e 's|'$VIMWIKI_DIR'/||g' | \
    sort | tr '\n' ' ' | \
    rofi -dmenu -i -sep ' ' -p "Wiki" )

if [ -n "$wiki" ]; then
    if [ "$1" = "pdf" ]; then
        $HOME/bin/md2pdf ${VIMWIKI_DIR}/${wiki}.md 2> /dev/null &
    else
        urxvt -e sh -c "exec nvim -R ${VIMWIKI_DIR}/${wiki}.md" 2> /dev/null &
    fi
fi
