#!/bin/sh

# Find the password I want

OPTS="LOCK SCREEN|QUIT HERBSTLUFTWM|SYSTEM POWEROFF|SYSTEM REBOOT"

# Either pass what we want to do as an argument to the script
# or get it through rofi
systask="$@"
if [ -z $systask ]; then
    systask=$( echo $OPTS | rofi -sep '|' -dmenu -i -p "SYSTEM" -lines 4)
fi

if [ "$systask" = "LOCK SCREEN" ]; then

    exec i3lock -nefi $HOME/etc/xorg/hubble_legacy_field.png

elif [ "$systask" = "QUIT HERBSTLUFTWM" ]; then

    # This can't be safe...
    # TODO: Figure out a better way to poweroff from a script
    rofi -dmenu -input /dev/null -password -lines 0 -p "SUDO QUIT HERBSTLUFTWM" | \
        sudo -S herbstclient quit
    if [ "$?" -eq 1 ]; then
        rofi -e "Incorrect password..."
    fi

elif [ "$systask" = "SYSTEM POWEROFF" ]; then

    rofi -dmenu -input /dev/null -password -lines 0 -p "SUDO POWEROFF" | \
        sudo -S poweroff
    if [ "$?" -eq 1 ]; then
        rofi -e "Incorrect password..."
    fi

elif [ "$systask" = "SYSTEM REBOOT" ]; then

    rofi -dmenu -input /dev/null -password -lines 0 -p "SUDO REBOOT" | \
        sudo -S reboot
    if [ "$?" -eq 1 ]; then
        rofi -e "Incorrect password..."
    fi

fi
