#!/bin/sh

# Constantly running volume module

. $HOME/etc/lemonbar/config
. $HOME/etc/lemonbar/modules/volume/update_function
LOGGER=$(get_logger lemonbar.volume.const)

$LOGGER "Initializing volume module [constant]"

while true; do
    volume_status_update;
    sleep $REFRESH_VOLUME
done
