#!/bin/sh

# Event drive volume module

. $HOME/.config/lemonbar/config.default
. $HOME/etc/lemonbar/modules/volume/update_function
LOGGER=$(get_logger lemonbar.volume.event)

$LOGGER "Initializing volume module [event driven]"

while read -r volume_event; do
    (
        volume_status_update;
    ) &
done

# vim: set ft=sh:
