#!/bin/sh

# Event drive volume module

. $HOME/etc/lemonbar/config
. $HOME/etc/lemonbar/modules/volume/update_function

while read -r volume_event; do
    (
        $volume_event;
        volume_status_update;
    ) &
done

# vim: set ft=sh:
