#!/bin/sh

# Lemonbar Volume Update function

volume_status_update() {

    if [ $(pulsemixer --get-mute) -eq 0 ]; then
        msg="$(pulsemixer --get-volume | awk '{print $1}')%"
        color=$CYAN
    else
        msg="MUTE"
        color=$RED
    fi
    msg="%{B$color} ${ICON_VOLUME}$msg %{B-}%{F$color}"

    echo "$ANCHOR_VOLUME$msg"
}
