#!/bin/sh

userresources=$HOME/.xresources
usermodmap=$HOME/.xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

# We need to source some things if it exists

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Load the xresources
xrdb -I$HOME $HOME/lib/xorg/xresources

# Start the urxvt daemon
urxvtd -q -o -f

# We need to start the compositor as well
# If we would like to kill our CPU so no.
# But hey, it definetly looks crisp af tho.
# compton --config $HOME/etc/comptonrc &

# Start Window Manager
session=${1:-herbstluftwm}

case $session in
    herbstluftwm)
	    exec herbstluftwm -c $HOME/lib/herbstluftwm/init.sh;;
    *)
        exec $1;;
esac

