#!/usr/bin/env sh

# Sourced the xcolors init.sh
# . $HOME/lib/xorg/xcolor.sh

# Battery function

battery() {
    batloc="/sys/class/power_supply/"
    batlist=$(ls $batloc | grep "BAT")
    out="[BAT"

    if [ -n "${batlist}" ]; then
        for bat in $batlist; do
            cap="$(cat ${batloc}${bat}/capacity)"
            stat="$(cat ${batloc}${bat}/status)"
            batid=$(echo $bat | tr -d 'BAT')

            if [ "$stat" = "Charging" ]; then
                out="${out} ${batid}:%{F${GREEN}}${cap}%%{F-}"

            elif [ $cap -le 5 ]; then
                out="${out} ${batid}:%{F${RED}}${cap}%%{F-}"

            elif [ $cap -le 25 ]; then
                out="${out} ${batid}:%{F${YELLOW}}${cap}%%{F-}"

            else
                out="${out} ${batid}:%{F${CYAN}}${cap}%%{F-}"
            fi

        done
    else
        out="${out} %{F${CYAN}}A/C%{F-}"
    fi

    out="${out}]"

    echo -n $out
}
