#!/usr/bin/env sh

# Sourced the xcolors init.sh
# . $HOME/lib/xorg/xcolor.sh

# Network function
#   Uses nmcli and ip for network info,

network() {
    net=$(nmcli -t device status | grep 'connected')

    # If we aren't connected
    if [ -z "${net}" ]; then
        net=$(ip -br addr | grep 'UNKNOWN')

        color=${RED}
        DEVICE=$(echo $net | awk '{print $1}')

        SSID="localhost"
        IP=$(echo $net | awk '{print $3}')

    # If we are connected
    else
        color=${MAGENTA}
        DEVICE=$(echo $net | sed 's/:.*//g')

        # Replace the SSID with the word ethernet if its ethernet
        if [ -z "$(echo $net | grep 'ethernet')" ]; then
            SSID=$(echo $net | sed 's/.*://g')
        else
            SSID="Ethernet"
        fi

        IP=$(ip -br addr | grep $DEVICE | awk '{print $3}')
    fi

    IPTMP='/tmp/.iptempfile'

    if [ -f "$IPTMP" ]; then
        out="[%{A:rm $IPTMP:}NET %{F${color}}${DEVICE}: ${SSID}"
        out="$out ($IP)%{F-}%{A}]"
    else
        out="[%{A:touch $IPTMP:}NET %{F${color}}${DEVICE}: ${SSID}%{F-}%{A}]"
    fi

    echo -n $out
}
