#!/usr/bin/env sh

# Sourced the xcolors init.sh
# . $HOME/lib/xorg/xcolor.sh

# Network function
#   Uses nmcli and ip for network info,

network() {
    net=$(nmcli -t device status | grep 'connected')

    if [ -z "${net}" ]; then
        color=${RED}
        # Grab info about localhost from ip
        net=$(ip -br addr | grep 'UNKNOWN')
        DEVICE=$(echo $net | awk '{print $1}')
        CONNECTION=$(echo $net | awk '{print $3}')
    else
        color=${MAGENTA}
        DEVICE=$(echo $net | sed 's/:.*//g')
        CONNECTION=$(echo $net | sed 's/.*://g')
    fi

    out="[NET %{F${color}}${DEVICE}: ${CONNECTION}%{F-}]"
    echo -n $out
}
