#!/usr/bin/env sh

# Sourced the xcolors init.sh
# . $HOME/lib/xorg/xcolor.sh

# userathost function

userathost() {
    out="[USER %{F${RED}}$(whoami)@$(hostname) $(uname -r)%{F-}]"
    echo -n $out
}
