#!/usr/bin/env sh

# Sourced the xcolors init.sh
# . $HOME/lib/xorg/xcolor.sh

# Volume function
#   Needs alsa installed

volume() {
    
    status=$(amixer get Master | grep 'off')
    vol=$(amixer get Master | grep 'Front Left:' | \
            awk '{print $5}' | tr -d '[]')

    if [ -z "$status" ]; then
        out="[VOL %{F${CYAN}}${vol}%{F-}]"
    else
        out="[VOL %{F${RED}}MUTED%{F-}]"
    fi
    echo -n $out
}
