#!/bin/sh

# Import modules needed but anything that imports this config
. $HOME/lib/shell/xrdb_colors
. $HOME/etc/lemonbar/wrappers

# Config variables used by all components of lemonbar
# ---------------------------------------------------

# Primary FIFOs
PANEL_TOP_FIFO=/tmp/panel_top.fifo
PANEL_BOT_FIFO=/tmp/panel_bot.fifo

# Event FIFOs
EVENT_WSP_FIFO=/tmp/workspace_event.fifo
EVENT_WIN_FIFO=/tmp/wininfo_event.fifo

# Choose the output wrapper
MSG_WRAPPER=legacy_wrapper

# Specify the Anchor Character for each module
ANCHOR_BACKLIGHT='L'
ANCHOR_BATTERY='B'
ANCHOR_DATE='D'
ANCHOR_NETWORK='N'
ANCHOR_TIME='T'
ANCHOR_WHOAMI='U'
ANCHOR_WININFO='X'
ANCHOR_WORKSPACES='W'

# Refresh rates of non-event based modules
REFRESH_BACKLIGHT=1
REFRESH_BATTERY=2
REFRESH_DATE=86400
REFRESH_NETWORK=2
REFRESH_TIME=1

# Icons for various modules
ICON_BACKLIGHT="BKL"
ICON_BATTERY="BAT"
ICON_DATE="DATE"
ICON_NETWORK="NET"
ICON_TIME="TIME"
ICON_WHOAMI="USER"
ICON_WININFO="WIN"
ICON_WORKSPACES="WSP"

# Hardware Specification
WLAN0="wlp82s0"
ETHO0="enp0s31f6"
