#!/bin/sh

# Import modules needed but anything that imports this config
. $HOME/lib/shell/xrdb_colors
. $HOME/etc/lemonbar/utils/wrappers
. $HOME/etc/lemonbar/utils/multi_monitor_support
. $HOME/etc/lemonbar/utils/logger

# Source local system config in case there are system specific changes
. $HOME/.config/lemonbar/config

# Config variables used by all components of lemonbar
# ---------------------------------------------------

# Primary FIFOs
PANEL_TOP_FIFO=/tmp/panel_top.fifo
PANEL_BOT_FIFO=/tmp/panel_bot.fifo

# Event FIFOs
EVENT_BKL_FIFO=/tmp/backlight_event.fifo
EVENT_VOL_FIFO=/tmp/volume_event.fifo
EVENT_WSP_FIFO=/tmp/workspace_event.fifo
EVENT_WIN_FIFO=/tmp/wininfo_event.fifo

# Choose the output wrapper
MSG_WRAPPER=icon_wrapper

# Specify the Anchor Character for each module
ANCHOR_BACKLIGHT='L'
ANCHOR_BATTERY='B'
ANCHOR_CPU='C'
ANCHOR_DATE='D'
ANCHOR_FILESYSTEMS='F'
ANCHOR_MEMORY='M'
ANCHOR_NETWORK='N'
ANCHOR_SWAP='S'
ANCHOR_SPOTIFY='J'
ANCHOR_TIME='T'
ANCHOR_WHOAMI='U'
ANCHOR_WININFO='X'
ANCHOR_WORKSPACES='W'
ANCHOR_VOLUME='V'

# Refresh rates of non-event based modules
REFRESH_BATTERY=2
REFRESH_CPU=3
REFRESH_DATE=86400
REFRESH_FILESYSTEMS=10
REFRESH_MEMORY=3
REFRESH_NETWORK=2
REFRESH_SWAP=3
REFRESH_TIME=1

# Font Awesome icons for various modules
# https://fontawesome.com/icons?d=gallery&m=free
if [ -z "$LEMONBAR_DISABLE_ICONS" ]; then
    ICON_BACKLIGHT=$(env printf "\uf042 ")
    ICON_BATTERY_AC=$(env printf "\uf1e6 ")
    ICON_BATTERY_EMPTY=$(env printf "\uf244 ")
    ICON_BATTERY_NEAR_EMPTY=$(env printf "\uf243 ")
    ICON_BATTERY_HALF=$(env printf "\uf242 ")
    ICON_BATTERY_NEAR_FULL=$(env printf "\uf241 ")
    ICON_BATTERY_FULL=$(env printf "\uf240 ")
    ICON_BATTYER_CHARGING=$ICON_BATTERY_AC
    ICON_CPU=$(env printf "\uf24d ")
    ICON_DATE=$(env printf "\uf073 ")
    ICON_FILESYSTEMS=$(env printf "\uf0a0 ")
    ICON_MEMORY=$(env printf "\uf538 ")
    ICON_MUSIC=$(env printf "\uf001 ")
    ICON_NETWORK_ETHERNET=$(env printf "\uf796 ")
    ICON_NETWORK_OFFLINE=$(env printf "\uef6ff ")
    ICON_NETWORK_WIFI=$(env printf "\uf1eb ")
    ICON_SWAP=$(env printf "\uf1c0 ")
    ICON_TIME=$(env printf "\uf017 ")
    ICON_WHOAMI=$(env printf "\uf007 ")
    ICON_LINUX=$(env printf "\uf120 ")
    ICON_WORKSPACES=$(env printf "\uf108 ")
    ICON_VOLUME=$(env printf "\uf025 ")
else
    # Some icons are better left as blank so not all are defined
    ICON_BACKLIGHT="bL: "
    ICON_BATTERY_EMPTY="bat: "
    ICON_BATTERY_NEAR_EMPTY=$ICON_BATTERY_EMPTY
    ICON_BATTERY_HALF=$ICON_BATTERY_EMPTY
    ICON_BATTERY_NEAR_FULL=$ICON_BATTERY_EMPTY
    ICON_BATTERY_FULL=$ICON_BATTERY_EMPTY
    ICON_BATTERY_CHARGING="a/c: "
    ICON_CPU="cpu: "
    ICON_MEMORY="mem: "
    ICON_SWAP="swap: "
    ICON_VOLUME="vol: "
fi

# Powerline Icons
PL_R=$(env printf "\ue0b0")
PL_Rb=$(env printf "\ue0b1")
PL_L=$(env printf "\ue0b2")
PL_Lb=$(env printf "\ue0b3")

# Hardware Specification
WIFI_INTERFACE=${WIFI_INTERFACE:-"wlp82s0"}
ETHERNET_INTERFACE=${ETHERNET_INTERFACE:-"enp0s31f6"}
FILESYSTEMS=${FILESYSTEMS:-"/dev/nvme0n1p4 /home/zamlz/tmp"}
