#!/bin/sh
#  _                            _                                         _
# | | ___ _ __ ___   ___  _ __ | |__   __ _ _ __   _ __   __ _ _ __   ___| |
# | |/ _ \ '_ ` _ \ / _ \| '_ \| '_ \ / _` | '__| | '_ \ / _` | '_ \ / _ \ |
# | |  __/ | | | | | (_) | | | | |_) | (_| | |    | |_) | (_| | | | |  __/ |
# |_|\___|_| |_| |_|\___/|_| |_|_.__/ \__,_|_|    | .__/ \__,_|_| |_|\___|_|
#                                                 |_|
# New and improved lemonbar script

# Import xresource colors
. $HOME/lib/shell/xrdb_colors
. $HOME/etc/lemonbar/wrappers

# GLOBALS
PANEL_TOP_FIFO=/tmp/panel_top.fifo
PANEL_BOT_FIFO=/tmp/panel_bot.fifo

# Avoid running the panel multiple times
if [ $(pgrep -cx lemonbar) -gt 1 ]; then
    printf "The panel is already running.\n" >&2
    exit 1
fi

# Exit gracefully if terminated
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# Remove old fifo files and add this one
[ -e "$PANEL_TOP_FIFO" ] && rm $PANEL_TOP_FIFO
[ -e "$PANEL_BOT_FIFO" ] && rm $PANEL_BOT_FIFO
mkfifo $PANEL_TOP_FIFO; mkfifo $PANEL_BOT_FIFO

# Set the message wrapper to be used
MSG_WRAPPER=legacy_wrapper

# Add modules to the top fifo
. $HOME/etc/lemonbar/modules/backlight  > $PANEL_TOP_FIFO &
. $HOME/etc/lemonbar/modules/battery    > $PANEL_TOP_FIFO &
. $HOME/etc/lemonbar/modules/calendar   > $PANEL_TOP_FIFO &
. $HOME/etc/lemonbar/modules/clock      > $PANEL_TOP_FIFO &
. $HOME/etc/lemonbar/modules/userathost > $PANEL_TOP_FIFO &
. $HOME/etc/lemonbar/modules/windowinfo > $PANEL_TOP_FIFO &

# Add modules to the bot fifo
. $HOME/etc/lemonbar/modules/network    > $PANEL_BOT_FIFO &
. $HOME/etc/lemonbar/modules/workspaces > $PANEL_BOT_FIFO &

# Find th font to use.
font=$(xrdb -query \
    | grep '*font' \
    | sed -E "s/.*xft:(.*)/\\1/")

# Define lemonbar opts
OPTS="  -g x24
    -F ${XFOREGROUND}
    -B ${XBACKGROUND}
    -f ${font}
    -u 3"

# Start the top panel
$HOME/etc/lemonbar/loop TOP < $PANEL_TOP_FIFO | lemonbar $OPTS | sh &

# Start the bottom panel
$HOME/etc/lemonbar/loop BOT < $PANEL_BOT_FIFO | lemonbar $OPTS -b | sh &

wait

# vim: set ft=sh:
