#!/bin/sh
#  _                            _                                         _
# | | ___ _ __ ___   ___  _ __ | |__   __ _ _ __   _ __   __ _ _ __   ___| |
# | |/ _ \ '_ ` _ \ / _ \| '_ \| '_ \ / _` | '__| | '_ \ / _` | '_ \ / _ \ |
# | |  __/ | | | | | (_) | | | | |_) | (_| | |    | |_) | (_| | | | |  __/ |
# |_|\___|_| |_| |_|\___/|_| |_|_.__/ \__,_|_|    | .__/ \__,_|_| |_|\___|_|
#                                                 |_|
# New and improved lemonbar script

. $HOME/etc/lemonbar/config

# Avoid running the panel multiple times
if [ $(pgrep -cx lemonbar) -gt 1 ]; then
    printf "The panel is already running.\n" >&2
    exit 1
fi

# Exit gracefully if terminated
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# Prepare the FIFOS
$HOME/etc/lemonbar/utils/make_fifos

# Add modules to the top fifo
$HOME/etc/lemonbar/modules/backlight    < $EVENT_BKL_FIFO > $PANEL_TOP_FIFO &
$HOME/etc/lemonbar/modules/date         > $PANEL_TOP_FIFO &
$HOME/etc/lemonbar/modules/network      > $PANEL_TOP_FIFO &
$HOME/etc/lemonbar/modules/time         > $PANEL_TOP_FIFO &
$HOME/etc/lemonbar/modules/whoami       > $PANEL_TOP_FIFO &
$HOME/etc/lemonbar/modules/battery      > $PANEL_TOP_FIFO &

# Add modules to the bot fifo
$HOME/etc/lemonbar/modules/cpu          > $PANEL_BOT_FIFO &
$HOME/etc/lemonbar/modules/memory       > $PANEL_BOT_FIFO &
$HOME/etc/lemonbar/modules/workspaces   < $EVENT_WSP_FIFO > $PANEL_BOT_FIFO &
$HOME/etc/lemonbar/modules/volume       < $EVENT_VOL_FIFO > $PANEL_BOT_FIFO &
# $HOME/etc/lemonbar/modules/windowinfo   < $EVENT_WIN_FIFO > $PANEL_BOT_FIFO &

# Define lemonbar opts
OPTS="  -g x24
    -F ${XFOREGROUND}
    -B ${XBACKGROUND}
    -f dina:size=8
    -f -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1
    -u 3"

# -f -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1
# -f -wuncon-siji-medium-r-normal--17-120-100-100-c-0-iso10646-1

# Start the top panel
$HOME/etc/lemonbar/utils/loop TOP < $PANEL_TOP_FIFO | lemonbar $OPTS | sh &

# Start the bottom panel
$HOME/etc/lemonbar/utils/loop BOT < $PANEL_BOT_FIFO | lemonbar $OPTS -b | sh &

# Start the window manager hooks
pkill -x herbsthooks
$HOME/etc/lemonbar/wm_events/herbsthooks &

wait

# vim: set ft=sh:
