#!/bin/sh

# Import xresource colors
. $HOME/lib/shell/xrdb_colors

MODE="$1"

while read -r line; do
    # echo "Current line: $line" >&2
    case $line in
        USERHOST*)
            # Save the user at host information
            user="${line#????????}"
            ;;
        CLOCK*)
            # record the current time to a variable
            clock="${line#?????}"
            ;;
        CALENDAR*)
            # record the current calendar date to a variable
            cal="${line#????????}"
            ;;
        BATTERY*)
            # Record the battery information
            bat="${line#???????}"
            ;;
    esac

    # Print the contents of our modules based on the mode
    if [ "$MODE" == "TOP" ]; then
        printf "%s\n" "%{l}${user}%{c}%{r}${bat}${cal}${clock}"

    elif [ "$MODE" == "BOT" ]; then
        printf "%s\n" "%{l}%{c}%{r}"

    else
        printf "Panel loop given incorrect mode!\n" >&2
    fi
done
