#!/bin/sh

MODE="$1"

while read -r line; do
    # echo "Current line: $line" >&2
    case $line in
        BACKLIGHT*)
            bkl="${line#?????????}" ;;
        BATTERY*)
            bat="${line#???????}" ;;
        DATE*)
            cal="${line#????}";;
        NETWORK*)
            net="${line#???????}" ;;
        TIME*)
            clock="${line#?????}" ;;
        USERHOST*)
            user="${line#????????}" ;;
        WININFO*)
            win="${line#???????}" ;;
        WORKSPACE*)
            wsp="${line#?????????}" ;;
    esac

    # Print the contents of our modules based on the mode
    if [ "$MODE" == "TOP_FULL" ]; then
        m1="%{S0}%{c}$user"
        m2="%{S1}%{c}$win"
        m3="%{S2}%{l}$bat%{c}$cal$clock%{r}$bkl"
        printf "%s\n" "$m1$m2$m3"

    elif [ "$MODE" == "TOP" ]; then
        m1="%{l}$user"
        m2="%{c}$win"
        m3="%{r}$cal$clock"
        printf "%s\n" "$m1$m2$m3"

    elif [ "$MODE" == "BOT" ]; then
        m1="%{l}"
        m2="%{c}$wsp"
        m3="%{r}$bkl$net$bat"
        printf "%s\n" "$m1$m2$m3"

    else
        printf "Panel loop given incorrect mode!\n" >&2
    fi
done
