#!/bin/zsh

PYTHON_VENVS_DIR=${PYTHON_VENVS_DIR:-$HOME/.venvs}

# A simple wrapper for virtualenv
if [[ ! -z "$@" ]]; then
    vname=$1;
    shift;
    if [[ -z "$@" ]]; then
        if [[ ! -d "$PYTHON_VENVS_DIR/$vname" ]]; then
            echo "Create a new virtual environment named '$vname' ?";
            echo 'Press any key to continue or Ctrl+C to exit...\n'
            # note this is zsh read
            read -k1 -rs
            echo "Creating new venv: $vname";
            python -m venv $PYTHON_VENVS_DIR/$vname
        fi
        echo "Starting venv: $vname"
        source $PYTHON_VENVS_DIR/${vname}/bin/activate
        save_window_info
    else
        python -m venv $PYTHON_VENVS_DIR/$vname $@
        save_window_info
    fi
else
    echo "Python Virtual Environments (venvs)"
    tree -L 1 -d --noreport $PYTHON_VENVS_DIR/ | tail -n +2
fi
