#!/bin/zsh

VIMWIKI_DIR=${VIMWIKI_DIR:-$HOME/usr/wiki}

if [[ $# == 0 ]]; then
    vim -c VimwikiIndex

elif [[ $1 == 'git' ]]; then
    git -C ${VIMWIKI_DIR} ${@:2}

elif [[ $1 == 'tree' ]]; then
    tree ${VIMWIKI_DIR} ${@:2}

else
    echo "Usage: ${0} [git] [args ...]"
fi
