#!/bin/zsh

# Get current terminal sessions info
function window_info() {
    echo "WINDOW_PWD='$(pwd)'";
    echo "VIRTUAL_ENV='${VIRTUAL_ENV}'";
}

function save_window_info() {
    window_info > /tmp/.wid_${WINDOWID}
}

# This is a special alias that overrides the
# default behaviour of cd.
# instead it makes cd behave such that it saves the
# directory that we enter.
if [ -n "$DISPLAY" ]; then

    # Build our custom cd
    function cd () {
        builtin cd $@
        save_window_info
    }

    # Every terminal should generate its id file on spawn
    if [ -z "$WINDOWID" ]; then
        echo "Terminal doesn't have a Window ID!!!"
    else
        save_window_info
    fi
fi
