#!/bin/zsh

XCOLORSCHEME_DIR=$HOME/lib/colorschemes
XCOLORSCHEME_TARGET=$HOME/.config/xcolor/scheme

# Simple symlink setter for changing the colorscheme
if [ -z "$1" ]; then
    ls $XCOLORSCHEME_DIR
else
    rm $XCOLORSCHEME_TARGET
    ln -s $XCOLORSCHEME_DIR/$1 $XCOLORSCHEME_TARGET
fi
