#!/bin/zsh

XCOLORSCHEME_DIR=$HOME/lib/colorschemes
XCOLORSCHEME_TARGET=$HOME/.config/xcolorscheme

# A special function for changing the colorscheme
function xcolorscheme() {
    if [ -z "$1" ]; then
        ls $XCOLORSCHEME_DIR
    else
        rm $XCOLORSCHEME_TARGET
        ln -s $XCOLORSCHEME_DIR/$1 $XCOLORSCHEME_TARGET
    fi
}
