#!/bin/sh

# WARNING: THIS CODE IS DANGEROUS
# This must be fixed at some point to utilize proper escaping of the
# $namepsace argument. As it stands now, the code has the potential
# to be misused and let other commands be injected in. Luckily, it is
# only used internally and deliberately. Regardless, use with
# caution!!!

_get_namespace() {
    ns=$(readlink -f $1 \
        | sed -e "s|$HOME/||g" \
        | tr -t / .)
    echo "$(whoami)/${ns}"
}

get_logger() {
    opts="--tag '$(_get_namespace $1) [$$]'"
    opts="--stderr $opts"
    echo "logger() { /usr/bin/logger $opts \$@; }"
}

get_logger_no_stderr() {
    opts="--tag '$(_get_namespace $1) [$$]'"
    echo "logger() { /usr/bin/logger $opts \$@; }"
}
