#!/bin/sh

. $HOME/etc/lemonbar/config
MODE="$1"

while read -r line; do
    # echo "Current line: $line" >&2
    case $line in
        $ANCHOR_BACKLIGHT*)     bkl="${line#?}" ;;
        $ANCHOR_BATTERY*)       bat="${line#?}" ;;
        $ANCHOR_CPU*)           cpu="${line#?}" ;;
        $ANCHOR_DATE*)          cal="${line#?}" ;;
        $ANCHOR_MEMORY*)        mem="${line#?}" ;;
        $ANCHOR_NETWORK*)       net="${line#?}" ;;
        $ANCHOR_SWAP*)          swp="${line#?}" ;;
        $ANCHOR_TIME*)          clk="${line#?}" ;;
        $ANCHOR_WHOAMI*)        usr="${line#?}" ;;
        $ANCHOR_WININFO*)       win="${line#?}" ;;
        $ANCHOR_WORKSPACES*)    wsp="${line#?}" ;;
        $ANCHOR_VOLUME*)        vol="${line#?}" ;;
    esac

    # Print the contents of our modules based on the mode
    if [ "$MODE" == "TOP_FULL" ]; then
        m1="%{S0}%{c}$usr"
        m2="%{S1}%{c}$win"
        m3="%{S2}%{l}$bat%{c}$cal$clk%{r}$bkl"
        printf "%s\n" "$m1$m2$m3"

    elif [ "$MODE" == "TOP" ]; then
        m1="%{l}$usr"
        m2="%{c}$cal$clk"
        m3="%{r}$bkl$net$bat"
        printf "%s\n" "$m1$m2$m3"

    elif [ "$MODE" == "BOT" ]; then
        m1="%{l}$vol"
        m2="%{c}$win$wsp"
        m3="%{r}$cpu$mem$swp"
        printf "%s\n" "$m1$m2$m3"

    else
        printf "Panel loop given incorrect mode!\n" >&2
    fi
done
