#!/bin/sh

. $HOME/etc/lemonbar/config
MODE="$1"

# Define the monitors
if [ -f $TRIPLE_MONITOR_TOGGLE ]; then
MONITOR_1="%{S0}%{c}"
MONITOR_2="%{S1}%{c}"
MONITOR_3="%{S2}%{c}"
else
MONITOR_1="%{S0}%{l}"
MONITOR_2="%{S0}%{c}"
MONITOR_3="%{S0}%{r}"
fi

while read -r line; do
    # echo "Current line: $line" >&2
    case $line in
        $ANCHOR_BACKLIGHT*)     bkl="${line#?}" ;;
        $ANCHOR_BATTERY*)       bat="${line#?}" ;;
        $ANCHOR_CPU*)           cpu="${line#?}" ;;
        $ANCHOR_DATE*)          cal="${line#?}" ;;
        $ANCHOR_MEMORY*)        mem="${line#?}" ;;
        $ANCHOR_NETWORK*)       net="${line#?}" ;;
        $ANCHOR_SWAP*)          swp="${line#?}" ;;
        $ANCHOR_TIME*)          clk="${line#?}" ;;
        $ANCHOR_WHOAMI*)        usr="${line#?}" ;;
        $ANCHOR_WININFO*)       win="${line#?}" ;;
        $ANCHOR_WORKSPACES*)    wsp="${line#?}" ;;
        $ANCHOR_VOLUME*)        vol="${line#?}" ;;
    esac

    # Print the contents of our modules based on the mode
    if [ "$MODE" == "TOP_FULL" ]; then
        m1="%{S0}%{c}$usr"
        m2="%{S1}%{c}$win"
        m3="%{S2}%{l}$bat%{c}$cal$clk%{r}$bkl"
        printf "%s\n" "$m1$m2$m3"

    elif [ "$MODE" == "TOP" ]; then
        m1="${MONITOR_1}$usr"
        m2="${MONITOR_2}$cal$clk"
        m3="${MONITOR_3}$bkl$net$bat"
        printf "%s\n" "$m1$m2$m3"

    elif [ "$MODE" == "BOT" ]; then
        m1="${MONITOR_1}$vol"
        m2="${MONITOR_2}$win$wsp"
        m3="${MONITOR_3}$cpu$mem$swp"
        printf "%s\n" "$m1$m2$m3"

    else
        printf "Panel loop given incorrect mode!\n" >&2
    fi
done
