#!/bin/sh

# We use a sepeate script to send signals to the fifos that an event has
# occured since we don't want oother processes to really know the locations
# of these fifos in case they change.

. $HOME/etc/lemonbar/utils/where_fifos

# [ bkl wsp win vol ]
TRIGGER_FIFO=$1

if [ $TRIGGER_FIFO = "bkl" ]; then
    echo "." > $EVENT_BKL_FIFO

elif [ $TRIGGER_FIFO = "wsp" ]; then
    echo "." > $EVENT_WSP_FIFO

elif [ $TRIGGER_FIFO = "win" ]; then
    echo "." > $EVENT_WSP_FIFO

elif [ $TRIGGER_FIFO = "vol" ]; then
    echo "." > $EVENT_VOL_FIFO
fi
