#!/bin/sh

# Primary FIFOs
PANEL_TOP_FIFO=/tmp/panel_top.fifo
PANEL_BOT_FIFO=/tmp/panel_bot.fifo

# Event FIFOs
EVENT_BKL_FIFO=/tmp/backlight_event.fifo
EVENT_VOL_FIFO=/tmp/volume_event.fifo
EVENT_WSP_FIFO=/tmp/workspace_event.fifo
EVENT_WIN_FIFO=/tmp/wininfo_event.fifo
