#!/bin/sh

# Minimal wrapper
legacy_wrapper() {
    icon=$1 && shift && color=$1 && shift && msg=$@
    echo -ne "[$icon %{F$color}$msg%{F-}]"
}

icon_wrapper() {
    icon=$1 && shift && color=$1 && shift && msg=$@
    echo -ne " $icon %{F$color}$msg%{F-} "
}

# debug wrapper for testing
debug_wrapper() {
    icon=$1 && shift && color=$1 && shift && msg=$@
    echo -ne "[DEBUG $icon $color $msg]"
}
