#!/bin/sh

. $HOME/lib/shell/logger
LOGGER=$(get_logger xorg.wminit)
$LOGGER "Initializing window manager common utilities"

# We need to start the compositor as well
# If we would like to kill our CPU so no.
# But hey, it definetly looks crisp af tho.
pkill -x compton
if [ -f "$HOME/.config/xcompton" ]; then
    $LOGGER "Starting Compton"
    compton --config $HOME/etc/compton/rc &
fi

# Reload the xresource data
xrdb -I$HOME $HOME/etc/xorg/xresources

#if [ -z "$(pgrep urxvtd)" ]; then
#    urxvtd -q -o -f
#fi

# Once colors have been reloaded, generate env variables for them
. $HOME/lib/shell/xrdb_colors

# Set the background
if [ -f "$HOME/.fehbg" ]; then
    $HOME/.fehbg
else
    xsetroot -bitmap ~/lib/bitmaps/tile.xbm -fg '#232323' -bg '#0a0a0a'
fi

# Initialize universal keybindings
SXHKD_SHELL=sh
export SXHKD_TERMINAL=urxvt
pkill -x sxhkd
sxhkd -c "$HOME/etc/sxhkd/keybinds" &

# Also have to set this here in case xorg isn't started via startx
setxkbmap -option caps:escape

# Use Display Power Management Settings to configure various things.
# + Disable screen blanking (screensaver) (I don't think this works)
xset s off
# + Increases the speed of the keyboard repeat rate
xset r rate 400 50

# Rehash local fonts
xset +fp $HOME/.local/share/fonts
xset fp rehash

# Start dunst to catch notifications
pkill -x dunst
#dunst &

# Start lemonbar after all X related stuff is finished
pkill -x lemonbar
$HOME/etc/lemonbar/lemonbar &
