#!/bin/sh

# We need to source some things if it exists
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Repeat for any local scripts if they exist
# Store xrandr monitor setup scripts here!!!
if [ -d $HOME/.config/xinitrc.d ] ; then
    find "$HOME/.config/xinitrc.d" -name "*.sh" | while read -r f; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Start Window Manager
session=${1:-herbstluftwm}

case $session in
    herbstluftwm)   exec herbstluftwm -c $HOME/etc/herbstluftwm/init;;
    *)              exec $1;;
esac

