#!/bin/sh

# We need to source some things if it exists

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Specify some special keymaps
setxkbmap -option caps:super
setxkbmap -option super:caps

# We need to start the compositor as well
# If we would like to kill our CPU so no.
# But hey, it definetly looks crisp af tho.
compton --config $HOME/etc/compton/rc &

# Start Window Manager
session=${1:-herbstluftwm}

case $session in
    herbstluftwm)   exec herbstluftwm -c $HOME/etc/herbstluftwm/init;;
    *)              exec $1;;
esac

