#!/bin/sh

# We need to source some things if it exists

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Start Window Manager
session=${1:-herbstluftwm}

case $session in
    herbstluftwm)   exec herbstluftwm -c $HOME/etc/herbstluftwm/init;;
    pyxwm)          exec $HOME/.venvs/pyxwm/bin/ipython -i \
                         $HOME/src/pyxwm/examples/run.py ;;
    *)              exec $1;;
esac

