#!/bin/zsh

# The LS Family Aliases
alias ls="LC_COLLATE=C ls -F --color=always"
alias ll="ls -l"
alias la="ls -la"

# Clearning fix
alias clear="TERM='xterm' clear"
alias eselect="TERM='xterm' eselect"

# PRETTY COLORS
alias grep="grep --color=always"
alias tree="tree -C"
alias dog="pygmentize"

# Config override
alias neofetch="neofetch --config $HOME/etc/neofetchrc"
alias tmux="tmux -f $HOME/etc/tmuxrc"
alias irc="weechat"
alias rss="newsboat --config-file=$HOME/lib/newsboat/config \
                    --url-file=$HOME/lib/newsboat/urls"

# Random Stuff
alias fping="ping -c 3 www.google.com"

# Teleportation Jutsu
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"

# Teleport to root of git repo
groot() {
    cd $(git rev-parse --show-toplevel);
    BRANCH=$(git branch --list --no-color );
    BRANCH=$(echo $BRANCH | cut -d " " -f 2);
    BRANCH=$(echo $BRANCH | tr -d '\n');
    figlet $BRANCH;
    git status;
}

# Teleport to my usc dir
alias usc='cd ~/src/usc; groot; '
# Teleport to my dotfiles
alias dots='cd; groot;'

# Information Functions
info() {
    clear
    echo
    neofetch
    echo
    colors
    echo
}

infos() {
    info
    scrot --delay 3 --count --quality 100 ~/.myscrot.png
    imgur ~/.myscrot.png
    rm ~/.myscrot.png
}

# Evaluate a README file
readme() {
    README=$(/bin/ls | /bin/grep -i "README")
    if [ ! -z $README ]; then
        less $README;
    fi;
}

# You done fucked up kiddo
if [ $UID -ne 0 ]; then
    alias fuck='eval "sudo $(fc -ln -1)"'
fi

# Other secure aliases (Force interactivitey)
alias rm="rm -I --preserve-root"
alias mv="mv -i"
alias cp="cp -i"

# Suffix Aliases
alias -s note=notes
alias -s png=sxiv
alias -s jpg=sxiv
alias -s jpeg=sxiv
alias -s pdf=mupdf

# Specially select a certain vim
if [ "nvim not found" != "$(which nvim)" ]; then
    alias vim=nvim;
fi

# Special Window manager Aliases
if [ "$WINDOW_MANAGER" = "bspwm" ]; then
    # This special cd command keeps track of directories externally
    cd() {
        if [ -z "$1" ]; then
            echo "$(readlink -f $HOME)" > $HOME/tmp/.$(bspc query -N -n)
            builtin cd
        else
            echo "$(readlink -f $1)" > $HOME/tmp/.$(bspc query -N -n)
            builtin cd $1
        fi
    }
fi
