#!/bin/zsh

# The LS Family Aliases
alias ls="LC_COLLATE=C ls -F --color=always"
alias ll="ls -l"
alias la="ls -la"

# The GIT Aliases
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gd="git diff"

# Clearning fix
alias clear="TERM='xterm' clear"
alias eselect="TERM='xterm' eselect"

# PRETTY COLORS
alias grep="grep --color=always"
alias tree="tree -C"
alias dog="pygmentize"

# Config override
alias neofetch="neofetch --config $HOME/etc/neofetchrc"
alias tmux="tmux -f $HOME/etc/tmuxrc"
alias irc="weechat"
alias rss="newsboat --config-file=$HOME/lib/newsboat/config \
    --url-file=$HOME/lib/newsboat/urls"

# Random Stuff
alias fping="ping -c 3 www.google.com"

# Teleportation Jutsu
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"

# Teleport to my usc dir
alias usc='cd ~/src/usc; groot; '
# Teleport to my dotfiles
alias dots='cd; groot;'

# Teleport to the root of a git directory
#   needs git and figlet
groot() {
    cd $(git rev-parse --show-toplevel);
    NAME=$(basename -s .git `git config --get remote.origin.url`)
    BRANCH=$(git branch --list --no-color | cut -d " " -f 2 | tr -d '\n');
    figlet -t -f slant $@ "${NAME}.${BRANCH}"
    git status
}


# Information Functions
info() {
    clear
    echo
    neofetch
    echo
    colors
    echo
}

infos() {
    info
    scrot --delay 3 --count --quality 100 ~/.myscrot.png
    imgur ~/.myscrot.png
    rm ~/.myscrot.png
}

# You done fucked up kiddo
if [ $UID -ne 0 ]; then
    alias fuck='eval "sudo $(fc -ln -1)"'
fi

# Other secure aliases (Force interactivitey)
alias rm="rm -I --preserve-root"
alias mv="mv -i"
alias cp="cp -i"

# Suffix Aliases
alias -s note=notes
alias -s png=sxiv
alias -s jpg=sxiv
alias -s gif=sxiv
alias -s jpeg=sxiv
alias -s pdf=zathura
alias -s md=md2pdf

# Specially select a certain vim
if [ "nvim not found" != "$(which nvim)" ]; then
    alias vim="nvim";
fi

# This is a special alias that overrides the
# default behaviour of cd.
# instead it makes cd behave such that it saves the
# directory that we enter.
if [ -n "$WINDOW_MANAGER" ]; then

# Build our custom cd
cd () {
    builtin cd $@
    pwd > ${HOME}/tmp/.wid_${WINDOWID}
}
# Terminal should generate its id file on spawn
pwd > ${HOME}/tmp/.wid_${WINDOWID}

fi
