#!/bin/zsh

# The LS Family Aliases
alias ls="LC_COLLATE=C ls -F --color=always"
alias ll="ls -l"
alias la="ls -la"

# The GIT Aliases
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gd="git diff"

# Clearing fix
alias clear="TERM='xterm' clear"
alias eselect="TERM='xterm' eselect"

# PRETTY COLORS
alias grep="grep --color=always"
alias tree="tree -C"
alias dog="pygmentize"

# Config override
alias neofetch="neofetch --config $HOME/etc/neofetch/rc"
alias tmux="tmux -f $HOME/etc/tmux/rc"
alias irc='WEECHAT_PASSPHRASE=$(pass social/irc/weechat) weechat'
alias rss="newsboat --config-file=$HOME/etc/newsboat/config \
--url-file=$HOME/etc/newsboat/urls"
alias ncmpcpp="ncmpcpp --config=$HOME/etc/ncmpcpp/config \
--bindings=$HOME/etc/ncmpcpp/bindings"

# Random Stuff
alias fping="ping -c 3 www.google.com"
alias weather="curl wttr.in"

# Teleportation Jutsu
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"

# Teleport to my school dirs
alias ucsc='cd ~/src/ucsc; groot; '
alias usc='cd ~/src/usc; groot; '

# Teleport to my dotfiles
alias dots='cd; groot;'

# Information Functions
alias info="clear;echo;neofetch;colors;"
alias infos="info;scrot --delay 3 --count --quality 100 ~/tmp/myscrot.png"

# You done fucked up kiddo
if [ $UID -ne 0 ]; then
    alias fuck='eval "sudo $(fc -ln -1)"'
fi

# Other secure aliases (Force interactivitey)
alias rm="rm -I --preserve-root"
alias mv="mv -i"
alias cp="cp -i"

# Suffix Aliases
alias -s png=sxiv
alias -s jpg=sxiv
alias -s gif=sxiv
alias -s jpeg=sxiv
alias -s pdf=zathura
alias -s md=md2pdf

# Specially select a certain vim
if [ "nvim not found" != "$(which nvim)" ]; then
    alias vim="nvim";
fi
