#!/usr/bin/env zsh

# Z Shell Aliases

# Shortcuts for ls
alias ls="LC_COLLATE=C ls -F --color=always"
alias ll="ls -oh"
alias la="ls -lah"

# Shell aliases to make using git easier.
alias gs='echo "origin = $(git remote get-url origin --push)" | lolcat; git status'
alias ga="git add"
alias gc="git commit"
alias gd="git diff"
alias gds="git diff --staged"
alias gl="git log --graph"
alias gls="git log --graph --stat"
alias gll="git log --graph --stat -p"
alias gllo="git log --graph --pretty=oneline --abbrev-commit"
alias glla="git log --graph --pretty=oneline --abbrev-commit --all"
alias gp="git push"
alias gf="git fetch"
alias gm="git merge"
alias gb="git branch -av"
alias gr="git rev-parse --show-toplevel"
alias grr="git rev-parse --show-toplevel | xargs"

# Make various commands pretty by default
alias grep="grep --color=always"
alias tree="tree -C"

# Misc things
alias fping="ping -c 3 www.google.com"
alias weather="curl wttr.in"

# Ricing info commands
alias info="clear;echo;neofetch;colors;"
alias infos="info;$HOME/bin/screenshot --delay 3"

# Sudo improvements...
alias please="sudo"
if [ $UID -ne 0 ]; then
    alias fuck='eval "sudo $(fc -ln -1)"'
fi

# Make certain commands safer to use by default
alias rm="rm -I --preserve-root"
alias mv="mv -i"
alias cp="cp -i"

# Config Overrides
alias tmux="tmux -f ~/etc/tmux/config"

# Develoepr Aliases
alias py="ipython"
