#!/bin/zsh

# The LS Family Aliases
alias ls="LC_COLLATE=C ls -F --color=always"
alias ll="ls -oh"
alias la="ls -lah"

# The GIT Aliases
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gd="git diff"
alias gds="git diff --staged"
alias gl="git log --graph --stat -p"
alias gp="git push"
alias gf="git fetch"
alias gm="git merge"
alias gb="git branch -av"

# Clearing fix
alias clear="TERM='xterm' clear"
alias eselect="TERM='xterm' eselect"

# PRETTY COLORS
alias grep="grep --color=always"
alias tree="tree -C"
alias dog="pygmentize"

# Random Stuff
alias fping="ping -c 3 www.google.com"
alias weather="curl wttr.in"

# Information Functions
alias info="clear;echo;neofetch;colors;"
alias infos="info;scrot --delay 3 --count --quality 100 ~/tmp/myscrot.png"

# Sudo stuff
alias please="sudo"

if [ $UID -ne 0 ]; then
    alias fuck='eval "sudo $(fc -ln -1)"'
fi

# Other secure aliases (Force interactivitey)
alias rm="rm -I --preserve-root"
alias mv="mv -i"
alias cp="cp -i"

# Specially select a certain vim
if [ "nvim not found" != "$(which nvim)" ]; then
    alias vim="nvim";
fi
