#!/bin/zsh

# Need a logger just to keep track of things
. $HOME/lib/shell/logging && eval "$(get_logger $0)"

if [ -z "$DISPLAY" ] && [ "$(fgconsole 2>/dev/null)" -eq 1 ]; then
    logger "Starting xinitrc parameterized on herbstluftwm"
    export WINDOW_MANAGER='herbstluftwm'
    exec startx $HOME/etc/xorg/xinitrc herbstluftwm

elif [ -z "$DISPLAY" ] && [ "$(fgconsole 2>/dev/null)" -eq 2 ]; then
    logger "Starting tmux session"
    export WINDOW_MANAGER='tmux'
    exec tmux -f $HOME/etc/tmux/config
fi
