#!/bin/zsh

# Various Settings
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE

# Changing Directories
setopt AUTO_CD
unsetopt BEEP # turn of audible beeps

bindkey -v

# Shell Completions
# (directory should exist if emacs tangled!)
autoload -Uz compinit && compinit -d "$HOME/.zsh.d/compdump"
autoload -U bashcompinit && bashcompinit
autoload -U promptinit && promptinit

# Source the important stuff
source $HOME/.zsh.d/aliases.zsh
source $HOME/.zsh.d/functions.zsh

# Configure SSH & GnuPG Variables
# - I don't know what to make of this. It appears it has to be here
#   and can't be in the .zshenv file. Need to investigate why
export GPG_TTY=$(tty)
export PINENTRY_USER_DATA='tty'
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket);

# Thanks to this wonderful command in ZSH prompt is always regenerated
# after every command!
#precmd() {
#    export PROMPT=$(prompt_generate)
#}

export PS1="%F{blue}%~%f %B%(?.%F{green}.%F{red})λ%f%b "

# Update our ls colors
eval $(dircolors -b $HOME/lib/shell/lscolors)

# Finally, if we are ina virtual environment start it
if [ -n "$VIRTUAL_ENV" ]; then
    source ${VIRTUAL_ENV}/bin/activate
fi

# This is for emacs vterm prompt tracking
vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)";
}
setopt PROMPT_SUBST
PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'
# This is for emacs vterm buffer name string
autoload -U add-zsh-hook
add-zsh-hook -Uz chpwd (){ print -Pn "\e]2;%m:%2~\a" }
