#!/bin/zsh

# History
export HISTSIZE=2000
export HISTFILE="$HOME/.zhistory"
export SAVEHIST=$HISTSIZE

# Various Settings
setopt hist_ignore_all_dups
setopt hist_ignore_space

# Miscellaneous Settings
setopt autocd
# setopt extendedglob
bindkey -v

# Shell Completions
autoload -U compinit
compinit

# Shell Correction
# setopt correctall

# Shell Prompt
autoload -U promptinit
promptinit

# Choose a prompt based on if we are in Xserver
# prompt adam1 background
# prompt adam2

# Generate our own custom prompt.
ps1_generate() {
    echo -ne "%B%F{cyan}.-"
    echo -ne "%F{black}(%b%F{cyan}%n%F{white}@%F{magenta}%M%F{black}%B)"
    echo -ne "%F{cyan}-%F{black}[%F{blue}%~%F{black}]"
    GIT_NAME=$(basename -s .git `git config --get remote.origin.url` 2> /dev/null)
    if [ -n "$GIT_NAME" ]; then
        GIT_BRANCH=$(git branch --list --no-color | cut -d " " -f 2 | tr -d '\n')
        # (yes/no add ; no commited)
        #GIT_YA=$(git status --porcelain 2>/dev/null| egrep "^M" | wc -l)
        #GIT_NA=$(git status --porcelain 2>/dev/null| egrep "^ M" | wc -l)
        GIT_NC=$(git status --porcelain 2>/dev/null| egrep "^(M| M | D)" | wc -l)
        # Use this info to construct our real status
        if [ $GIT_NC -eq 0 ]; then
        echo -ne "%F{cyan}-%F{black}<%F{green}$GIT_NAME.$GIT_BRANCH%F{black}>"
        else
        echo -ne "%F{cyan}-%F{black}<%F{red}$GIT_NAME.$GIT_BRANCH%F{black}>"
        fi
    fi
    if [ -n "$ENV_NAME" ]; then
        echo -ne "%F{cyan}-%F{black}{%F{yellow}$ENV_NAME%F{black}}"
    fi
    echo -ne "\n"
    echo -ne "%F{cyan}\`--%B%F{white}>%b "
}

precmd() {
    export PS1=$(ps1_generate)
}

# Update our ls colors
eval $(dircolors -b $HOME/lib/shell/lscolors)

# Necessary exports
export PATH="$HOME/bin:$PATH"
export HTOPRC="$HOME/etc/htop/rc"
export GPG_TTY=$(tty)

# Source our alises
source $HOME/etc/zsh/aliases

# Source some special programs
source $HOME/sys/path.sh 2> /dev/null

