#!/bin/zsh

# History
export HISTSIZE=2000
export HISTFILE="$HOME/.zhistory"
export SAVEHIST=$HISTSIZE

# Various Settings
setopt hist_ignore_all_dups
setopt hist_ignore_space

# Miscellaneous Settings
setopt autocd
# setopt extendedglob
bindkey -v

# Shell Completions
autoload -U compinit
compinit

# Shell Correction
# setopt correctall

# Shell Prompt
autoload -U promptinit
promptinit

# Choose a prompt based on if we are in Xserver
# prompt adam1 background
prompt adam2

# Update our ls colors
eval $(dircolors -b $HOME/lib/shell/lscolors)

# Necessary exports 
export PATH="$HOME/bin:$PATH"
export HTOPRC="$HOME/etc/htop/rc"
export GPG_TTY=$(tty)

# Source our alises
source $HOME/etc/zsh/aliases

# Source some special programs
source $HOME/sys/path.sh 2> /dev/null

