#!/bin/zsh

source $HOME/lib/repos

# Update the path variable
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin/:$PATH"

# Repo bin folders
export PATH="$LEDGER_DIR/bin:$PATH"
export PATH="$VIMWIKI_DIR/bin:$PATH"

# Random useful
export DISTRO=$(grep --color=none ^ID= /etc/os-release | sed -e 's/^ID=//g' \
    | tr -d '"')
export WSL=$(uname -r | grep "microsoft")

# Configure GnuPG Variables
# MAKE SURE THAT SSH CONFIG IS ALSO CONFIGURED!
export GPG_TTY=$(tty)
export PINENTRY_USER_DATA='tty'
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket);

# Other less variables
# (if on WSL, do this)
if [ -z "$WSL" ]; then
export LESS='-R --mouse --wheel-lines=3 --no-init --quit-if-one-screen'
else
export LESS='-R --no-init --quit-if-one-screen'
fi

# Other important directories
export PYTHON_VENVS_DIR="$HOME/.local/share/python-venvs"

# Configuration files (or of the sort)
export HTOPRC="$HOME/etc/htop/rc"
export TASKRC="$HOME/etc/taskwarrior/rc"
export LEDGER_FILE="$LEDGER_DIR/main.journal"

# Other random variables
export LESSHISTFILE="$HOME/.local/share/lesshst"
