#!/bin/zsh

# Update the path variable
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin/:$PATH"
export PATH="$HOME/lib/private/bin:$PATH"

# Random useful
export DISTRO=$(grep --color=none ^ID= /etc/os-release | sed -e 's/^ID=//g')

# Configure GnuPG Variables
export GPG_TTY=$(tty)
export PINENTRY_USER_DATA='tty'
# This part seems a little sketch...
# A lot of guides don't recommend setting this value
# until after gpg-agent exists
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket);

# Configuration files
export HTOPRC="$HOME/etc/htop/rc"
export TASKRC="$HOME/etc/taskwarrior/rc"
export PASSWORD_STORE_DIR="$HOME/usr/passwords"
export LEDGER_FILE="$HOME/usr/ledger/main.journal"

# Other less ariables
export LESS='-R --mouse --wheel-lines=3 --no-init --quit-if-one-screen'

# Other important directories
PYTHON_VENVS_DIRECTORY="$HOME/.local/share/python-venvs"
