#!/bin/sh

# P W D C F W
# Warp the newly spawned terminal to the
# (P)resent (W)orking (D)irectory of the
# (C)urrently (F)ocused (W)indow.
#
# Needs xdotool to be installed

# Assume its urxvt
urxvt -e sh -c "
    . /tmp/.wid_$(xdotool getwindowfocus);
    cd \${WINDOW_PWD};
    if [ -z \${VIRTUAL_ENV} ]; then
        exec zsh;
    else
        exec zsh -c \"export VIRTUAL_ENV=\${VIRTUAL_ENV}; zsh\"
    fi"

