
# __  __       _         __ _ _      
#|  \/  | __ _| | _____ / _(_) | ___ 
#| |\/| |/ _` | |/ / _ \ |_| | |/ _ \
#| |  | | (_| |   <  __/  _| | |  __/
#|_|  |_|\__,_|_|\_\___|_| |_|_|\___|
#                                    

###################################################

PDFEXE    = pdflatex --shell-escape
DVIEXE    = latex --shell-escape
PDFTEST   = mupdf

TEXSRC    = main.tex

OUTFILE   = ${TEXSRC:.tex=.pdf}

MISCFILE  = ${TEXSRC:.tex=.aux} \
	    ${TEXSRC:.tex=.log} \
	    ${TEXSRC:.tex=.dvi} \
	    ${TEXSRC:.tex=.out} \
	    ${TEXSRC:.tex=.bbl} \
	    ${TEXSRC:.tex=.blg} \
	    ${TEXSRC:.tex=.toc} \

MAKEARGS  = --no-print-directory -C

###################################################

all: ${TEXSRC} 
	-${PDFEXE} ${TEXSRC}

pdf: ${OUTFILE}
	-${PDFTEST} ${OUTFILE}

refresh: spotless pdf

clean:
	-rm -fv ${MISCFILE}

spotless: clean 
	-rm ${OUTFILE}

ci: spotless
	git add .
	git commit -e
