
# __  __       _         __ _ _
#|  \/  | __ _| | _____ / _(_) | ___
#| |\/| |/ _` | |/ / _ \ |_| | |/ _ \
#| |  | | (_| |   <  __/  _| | |  __/
#|_|  |_|\__,_|_|\_\___|_| |_|_|\___|
#

###################################################

PDFEXE    = pdflatex --shell-escape
DVIEXE    = latex --shell-escape
PDFTEST   = zathura
DVITEST   = dvi2tty

TEXSRC    = main.tex

OUTFILE   = ${TEXSRC:.tex=.pdf}
ENDFILE   = ${OUTFILE}

MISCFILE  = ${TEXSRC:.tex=.aux} \
			${TEXSRC:.tex=.log} \
			${TEXSRC:.tex=.dvi} \
			${TEXSRC:.tex=.out} \
			${TEXSRC:.tex=.bbl} \
			${TEXSRC:.tex=.blg} \
			${TEXSRC:.tex=.toc} \

###################################################

${ENDFILE}: ${TEXSRC}
	${PDFEXE} ${TEXSRC}
	mv ${OUTFILE} ${ENDFILE}

${ENDFILE:.pdf=.dvi}: ${TEXSRC}
	${DVIEXE} ${TEXSRC}
	mv ${OUTFILE:.pdf=.dvi} ${ENDFILE:.pdf=.dvi}

pdf: ${ENDFILE}
	-${PDFTEST} ${ENDFILE} &

dvi: ${ENDFILE:.pdf=.dvi}
	-${DVITEST} ${ENDFILE:.pdf=.dvi}

refresh: spotless pdf

clean:
	-rm -fv ${MISCFILE}

spotless: clean
	-rm ${OUTFILE}
	-rm ${OUTFILE:.pdf=.dvi}
	-rm ${ENDFILE}
	-rm ${ENDFILE:.pdf=.dvi}

ci: spotless
	git add .
	git commit -e

preview: spotless pdf
	while true; do \
		make PDFEXE="${PDFEXE} -interaction=nonstopmode" ${ENDFILE} > \
		/dev/null; \
		sleep 1; \
	done;
