#!/bin/sh

# P W D C F W
# Warp the newly spawned terminal to the
# (P)resent (W)orking (D)irectory of the
# (C)urrently (F)ocused (W)indow.

# Assume its urxvt
$@ -e sh -c "cd $(cat $HOME/tmp/.wid_$(xdotool getwindowfocus)); zsh"

