#!/usr/bin/env bash
if [[ -e /var/cache/eix/portage.eix ]]; then 
    cp -a /var/cache/eix/portage.eix /var/cache/eix/previous.eix; 
fi
eix-update > /dev/null
if [[ -e /var/cache/eix/previous.eix ]]; then 
    eix-diff > /dev/null; 
fi
